<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uiextensionmodel"
    nsURI="http:///org/eclipse/bpel/ui/uiextensionmodel.ecore" nsPrefix="org.eclipse.bpel.ui.uiextensionmodel">
  <eClassifiers xsi:type="ecore:EClass" name="ActivityExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnAlarmExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnEventExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnMessageExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartnerLinkExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partnerKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specCompliant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modificationStamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencePartnerLinks"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="advancedKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true"/>
  </eClassifiers>
</ecore:EPackage>
