package org.eclipse.php.internal.core.compiler.ast.parser.php54;

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////    $Id: php_compiler_ast_parser.cup,v 1.2 2012/01/18 08:16:07 zzhongwei Exp $
////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////


import java.util.*;
import org.eclipse.dltk.ast.*;
import org.eclipse.dltk.ast.declarations.*;
import org.eclipse.dltk.ast.expressions.*;
import org.eclipse.dltk.ast.references.*;
import org.eclipse.dltk.ast.statements.*;
import org.eclipse.php.internal.core.compiler.ast.nodes.*;
import org.eclipse.php.internal.core.compiler.ast.parser.*;
import org.eclipse.php.internal.core.ast.scanner.php54.*;

parser code {:

	class ModifierDocPair {
		public int modifier;
		public PHPDocBlock doc;
		
		public ModifierDocPair(int modifier, PHPDocBlock doc) {
			this.modifier = modifier;
			this.doc = doc;
		}
	}
	
	public Expression createDispatch(Expression dispatcher, Expression property) {

		if (property.getKind() == ASTNodeKinds.REFLECTION_CALL_EXPRESSION) {
			((ReflectionCallExpression) property).setReceiver (dispatcher);
			dispatcher = property;
		} else if (property.getKind() == ASTNodeKinds.METHOD_INVOCATION) {
			PHPCallExpression callExpression = (PHPCallExpression) property;
			dispatcher = new PHPCallExpression(dispatcher.sourceStart(), callExpression.sourceEnd(), dispatcher, callExpression.getCallName(), callExpression.getArgs());
		} else {
			dispatcher =  new FieldAccess(dispatcher.sourceStart(), property.sourceEnd(), dispatcher, property);
		}

		return dispatcher;
	}

	protected String getTokenName(int token) {
		return PhpTokenNames.getName(token);
	}
:}

/* terminals */

terminal  String T_EXIT;
terminal  T_IF;
terminal  String T_LNUMBER;
terminal  String T_DNUMBER;
terminal  String T_BNUMBER;
terminal  String T_STRING;
terminal  String T_STRING_VARNAME;
terminal  String T_VARIABLE;
terminal  String T_NUM_STRING;
terminal  T_INLINE_HTML;
terminal  String T_ENCAPSED_AND_WHITESPACE;
terminal  String T_CONSTANT_ENCAPSED_STRING;
terminal  T_ECHO;
terminal  T_DO;
terminal  T_WHILE;
terminal  T_ENDWHILE;
terminal  T_FOR;
terminal  T_ENDFOR;
terminal  T_FOREACH;
terminal  T_ENDFOREACH;
terminal  T_IN;
terminal  T_ENDDECLARE;
terminal  T_INSTANCEOF;
terminal  T_CLONE;
terminal  T_AS;
terminal  T_SWITCH;
terminal  T_ENDSWITCH;
terminal  T_CASE;
terminal  T_DEFAULT;
terminal  T_BREAK;
terminal  T_CONTINUE;
terminal  T_GOTO;
terminal  PHPDocBlock T_FUNCTION;
terminal  PHPDocBlock T_CONST;
terminal  T_RETURN;
terminal  T_TRY;
terminal  T_CATCH;
terminal  T_THROW;
terminal  T_USE;
terminal  T_GLOBAL;
terminal  PHPDocBlock T_VAR;
terminal  String T_UNSET;
terminal  String T_ISSET;
terminal  String T_EMPTY;
terminal  T_HALT_COMPILER;
terminal  PHPDocBlock T_CLASS;
terminal  T_OBJECT_OPERATOR;
terminal  T_DOUBLE_ARROW;
terminal  T_LIST;
terminal  T_ARRAY;
terminal  T_CLASS_C;
terminal  T_METHOD_C;
terminal  T_FUNC_C;
terminal  T_LINE;
terminal  String T_FILE;
terminal  String T_START_HEREDOC;
terminal  T_END_HEREDOC;
terminal  T_DOLLAR_OPEN_CURLY_BRACES;
terminal  T_CURLY_OPEN_WITH_DOLAR;
terminal  T_CURLY_OPEN;
terminal  T_CURLY_CLOSE;
terminal  T_PAAMAYIM_NEKUDOTAYIM;
terminal  T_NAMESPACE;
terminal  T_NS_C;
terminal  T_DIR;
terminal  T_NS_SEPARATOR;
terminal String T_VAR_COMMENT;
terminal String T_DEFINE;

terminal String T_INCLUDE,T_INCLUDE_ONCE,T_EVAL,T_REQUIRE,T_REQUIRE_ONCE;
terminal T_COMMA;
terminal String T_LOGICAL_OR,T_LOGICAL_XOR,T_LOGICAL_AND,T_PRINT;
terminal T_EQUAL;
terminal T_PLUS_EQUAL,T_MINUS_EQUAL,T_MUL_EQUAL,T_DIV_EQUAL,T_CONCAT_EQUAL,T_MOD_EQUAL,T_AND_EQUAL,T_OR_EQUAL,T_XOR_EQUAL,T_SL_EQUAL,T_SR_EQUAL;
terminal T_QUESTION_MARK;
terminal T_SEMICOLON;
terminal T_BOOLEAN_OR, T_BOOLEAN_AND;
terminal T_OR;
terminal T_KOVA;
terminal T_REFERENCE;
terminal T_IS_EQUAL,T_IS_NOT_EQUAL,T_IS_IDENTICAL,T_IS_NOT_IDENTICAL;
terminal T_IS_SMALLER_OR_EQUAL,T_IS_GREATER_OR_EQUAL;
terminal T_RGREATER;
terminal T_LGREATER;
terminal T_SL,T_SR;
terminal T_PLUS;
terminal T_MINUS;
terminal T_TIMES;
terminal T_DIV;
terminal T_PRECENT;
terminal T_NOT;
terminal T_TILDA;
//terminal T_NEKUDA;
terminal T_INC,T_DEC,T_INT_CAST,T_DOUBLE_CAST,T_STRING_CAST,T_ARRAY_CAST,T_OBJECT_CAST,T_BOOL_CAST,T_UNSET_CAST;
terminal T_AT;
terminal T_OPEN_RECT,T_CLOSE_RECT;
terminal T_NEW;
terminal T_ENDIF;
terminal T_ELSEIF;
terminal T_ELSE;
terminal PHPDocBlock T_STATIC;
terminal T_OPEN_PARENTHESE,T_CLOSE_PARENTHESE;
terminal T_NEKUDOTAIM;
terminal T_DOLLAR;
terminal T_QUATE,T_BACKQUATE;


//php 5.4
terminal T_INSTEADOF;
terminal PHPDocBlock T_TRAIT;
terminal T_CALLABLE;
terminal T_TRAIT_C;


/* Non terminals */

non terminal ModuleDeclaration thestart;
non terminal top_statement_list;
non terminal FullyQualifiedReference namespace_name;
non terminal List namespace_name_list;
non terminal List namespace_statement_list;
non terminal Statement top_statement;
non terminal Statement statement;
non terminal List inner_statement_list;
non terminal Statement inner_statement;
non terminal Statement unticked_statement;
non terminal PHPCallArgumentsList unset_variables;
non terminal Expression unset_variable;
non terminal Expression use_filename;
non terminal Expression foreach_optional_arg;
non terminal Expression foreach_variable;
non terminal Statement for_statement;
non terminal Statement foreach_statement;
non terminal Statement declare_statement;
non terminal List[] declare_list;
non terminal Block switch_case_list;
non terminal List case_list;
non terminal case_separator;
non terminal Statement while_statement;
non terminal List[] elseif_list;
non terminal List[] new_elseif_list;
non terminal Statement else_single;
non terminal Statement new_else_single;
non terminal List parameter_list;
non terminal List lexical_vars;
non terminal List lexical_var_list;
non terminal List non_empty_parameter_list;
non terminal FormalParameter parameter;
non terminal PHPCallArgumentsList function_call_parameter_list;
non terminal PHPCallArgumentsList non_empty_function_call_parameter_list;
non terminal List global_var_list;
non terminal Expression global_var;
non terminal List static_var_list;
non terminal class_statement_list;
non terminal class_statement;
non terminal Boolean is_reference;
non terminal List echo_expr_list;
non terminal List for_expr;
non terminal List non_empty_for_expr;
non terminal Expression expr_without_variable;
non terminal Expression function_call;
non terminal Expression exit_expr;
non terminal PHPCallArgumentsList ctor_arguments;
non terminal Expression common_scalar;
non terminal Expression static_scalar;
non terminal Expression scalar;
non terminal List static_array_pair_list;
non terminal possible_comma;
non terminal List non_empty_static_array_pair_list;
non terminal Expression expr;
non terminal Expression var_expr;
non terminal List nekudotaim_expr;
non terminal Expression reference_variable;
non terminal Expression variable_class_name;
non terminal Expression compound_variable;
non terminal Expression dim_offset;
non terminal Expression object_property;
non terminal Expression object_dim_list;
non terminal Expression variable_name;
non terminal Integer simple_indirect_reference;
non terminal List assignment_list;
non terminal Expression assignment_list_element;
non terminal List object_pair_list;
non terminal List non_empty_object_pair_list;
non terminal List array_pair_list;
non terminal List non_empty_array_pair_list;
non terminal List encaps_list;
non terminal List backticks_expr;
non terminal Expression encaps_var;
non terminal Expression encaps_var_offset;
non terminal Expression internal_functions_in_yacc;
non terminal String string_st;
non terminal PHPDocBlock interface_entry;
non terminal List interface_extends_list;

non terminal Expression w_variable;
non terminal Expression class_name;
non terminal TypeReference fully_qualified_class_name;
non terminal List class_variable_declaration;
non terminal List constant_declaration;
non terminal CompilerAstParser.ModifierDocPair method_modifiers;
non terminal Statement method_body;
non terminal Statement named_namespace_body;
non terminal Statement namespace_body;
non terminal CompilerAstParser.ModifierDocPair member_modifier;
non terminal PHPCallArgumentsList method_or_not;
non terminal List variable_properties;
non terminal PHPMethodDeclaration function_declaration_statement;
non terminal Statement class_declaration_statement;
non terminal Expression variable;
non terminal List additional_catches;
non terminal List non_empty_additional_catches;
non terminal CatchClause additional_catch;
non terminal PHPMethodDeclaration unticked_function_declaration_statement;
non terminal Statement unticked_class_declaration_statement;
non terminal CompilerAstParser.ModifierDocPair class_entry_type;
non terminal TypeReference extends_from;
non terminal List implements_list;
non terminal List interface_list;
non terminal TypeReference optional_class_type;
non terminal Expression r_variable;
non terminal CompilerAstParser.ModifierDocPair variable_modifiers;
non terminal Expression rw_variable;
non terminal Expression variable_without_objects;
non terminal Expression variable_property;
non terminal StaticFieldAccess static_member;
non terminal VariableReference tracked_variable;

non terminal Expression class_name_reference;
non terminal StaticConstantAccess class_constant;
non terminal Expression dynamic_class_name_reference;
non terminal Expression base_variable;
non terminal List dynamic_class_name_variable_properties;
non terminal Expression dynamic_class_name_variable_property;
non terminal StaticConstantAccess static_class_constant;
non terminal Expression base_variable_with_function_calls;

/* added the following rules for improving error recovery*/
non terminal Statement class_closure;
non terminal PHPMethodDeclaration function_body;
non terminal errorOrNot;

//php5.4
non terminal TraitUseStatement trait_use_statement;
non terminal List trait_list;
non terminal List trait_adaptations;
non terminal List trait_adaptation_list;
non terminal List non_empty_trait_adaptation_list;
non terminal TraitStatement trait_adaptation_statement;
non terminal TraitPrecedence trait_precedence;
non terminal List trait_reference_list;
non terminal Expression trait_method_reference;
non terminal FullyQualifiedTraitMethodReference trait_method_reference_fully_qualified;
non terminal TraitAlias trait_alias;
non terminal CompilerAstParser.ModifierDocPair trait_modifiers;

non terminal ChainingMethodPropertyList chaining_method_or_property;
non terminal PHPArrayDereferenceList chaining_dereference;
non terminal ChainingInstanceCall chaining_instance_call;
non terminal ChainingInstanceCall instance_call;
non terminal ClassInstanceCreation new_expr;

non terminal PHPCallArgumentsList method;
non terminal PHPCallArgumentsList array_method_dereference;
non terminal Expression array_function_dereference;

precedence left T_INCLUDE, T_INCLUDE_ONCE, T_EVAL, T_REQUIRE, T_REQUIRE_ONCE;
precedence left T_COMMA;
precedence left T_LOGICAL_OR;
precedence left T_LOGICAL_XOR;
precedence left T_LOGICAL_AND;
precedence right T_PRINT;
precedence left T_EQUAL, T_PLUS_EQUAL,T_MINUS_EQUAL,T_MUL_EQUAL,T_DIV_EQUAL,T_CONCAT_EQUAL,T_MOD_EQUAL,T_AND_EQUAL,T_OR_EQUAL,T_XOR_EQUAL,T_SL_EQUAL,T_SR_EQUAL;
precedence left T_QUESTION_MARK,T_SEMICOLON;
precedence left T_BOOLEAN_OR;
precedence left T_BOOLEAN_AND;
precedence left T_OR;
precedence left T_KOVA;
precedence left T_REFERENCE;

precedence nonassoc T_IS_EQUAL,T_IS_NOT_EQUAL,T_IS_IDENTICAL,T_IS_NOT_IDENTICAL;
precedence nonassoc T_RGREATER,T_IS_SMALLER_OR_EQUAL,T_LGREATER,T_IS_GREATER_OR_EQUAL;
precedence left T_SL,T_SR;
precedence left T_PLUS,T_MINUS;
precedence left T_TIMES,T_DIV,T_PRECENT;
precedence right T_NOT;
precedence nonassoc T_INSTANCEOF;
precedence right T_TILDA,T_INC,T_DEC,T_INT_CAST,T_DOUBLE_CAST,T_STRING_CAST,T_ARRAY_CAST,T_OBJECT_CAST,T_BOOL_CAST,T_UNSET_CAST,T_AT;
precedence right T_OPEN_RECT;
precedence nonassoc T_NEW, T_CLONE;
precedence left T_ELSEIF;
precedence left T_ELSE;
precedence left T_ENDIF;
precedence right T_STATIC;

thestart ::=
top_statement_list:statementList
{:
	PHPModuleDeclaration program = parser.getModuleDeclaration();

	PhpAstLexer phpAstLexer = (PhpAstLexer) parser.getScanner();
	List commentList = phpAstLexer.getCommentList();
	Iterator i = commentList.iterator();
	while (i.hasNext()) {
		Object c = i.next();
		if (c instanceof VarComment) {
			program.getVarComments().add((VarComment)c);
		} else if (c instanceof PHPDocBlock) {
			program.getPhpDocBlocks().add((PHPDocBlock) c);
		}
	}
	
	program.setStart(statementListleft);
	program.setEnd(statementListright + 1);
	RESULT = program; 
:}
;

namespace_name ::=
namespace_name_list:list
{:
	StringBuilder namespaceNameBuf = new StringBuilder();
	FullyQualifiedReference fullyQualifiedName = null;
	Iterator i = list.iterator();
	while (i.hasNext()) {
		String s = (String) i.next();
		if (i.hasNext()) {
			if (namespaceNameBuf.length() != 0) {
				namespaceNameBuf.append('\\');
			}
			namespaceNameBuf.append(s);
		} else {
			NamespaceReference namespaceRef = (namespaceNameBuf.length() != 0) ? 
				new NamespaceReference(listleft, listright - s.length() - 1, namespaceNameBuf.toString()) : null;
			fullyQualifiedName = new FullyQualifiedReference(listleft, listright, s, namespaceRef);
		}
	}
	RESULT = fullyQualifiedName;
:}
;

namespace_name_list ::=
string_st:name
{:
	List list = new LinkedList();
	list.add(name);
	RESULT = list;
:}
|
namespace_name_list:list T_OBJECT_OPERATOR string_st:name
{:
	list.add(name);
	RESULT = list;
:}
;



top_statement_list ::=
top_statement_list:statementList top_statement:statement
{:
	if(statement != null) {
		parser.addStatement(statement);
		if(parser.pendingStatement != null){
			parser.addStatement(parser.pendingStatement);
			parser.pendingStatement = null;
		}
	}
	while(!parser.declarations.isEmpty()) {
		parser.addStatement(parser.declarations.pop());
	}
:}

| /* empty */
;



top_statement ::=
statement:statement
{: 
	RESULT = statement;
:}

| function_declaration_statement:statement
{: 
	RESULT = statement; 
:}
| class_declaration_statement:statement
{: 
	RESULT = statement; 
:}
| T_NAMESPACE:start namespace_name:name
{:
	NamespaceDeclaration namespace = new NamespaceDeclaration(startleft, nameright, nameleft, nameright, name.getFullyQualifiedName(), null, null);
	parser.addDeclarationStatement(namespace);
	parser.declarations.push(namespace);
:}
named_namespace_body:body
{:
	RESULT = body;
:}
| T_VAR T_STRING:aliasName T_EQUAL T_REQUIRE:start T_OPEN_PARENTHESE T_CONSTANT_ENCAPSED_STRING:scalar T_CLOSE_PARENTHESE T_SEMICOLON:end
{:
	String module = scalar.substring(1,scalar.length()-1);
	List list = new LinkedList();
	list.add(module);
	StringBuilder namespaceNameBuf = new StringBuilder();
	FullyQualifiedReference fullyQualifiedName = null;
	Iterator i = list.iterator();
	while (i.hasNext()) {
		String s = (String) i.next();
		if (i.hasNext()) {
			if (namespaceNameBuf.length() != 0) {
				namespaceNameBuf.append('\\');
			}
			namespaceNameBuf.append(s);
		} else {
			NamespaceReference namespaceRef = (namespaceNameBuf.length() != 0) ? 
				new NamespaceReference(scalarleft, scalarright - s.length() - 1, namespaceNameBuf.toString()) : null;
			fullyQualifiedName = new FullyQualifiedReference(scalarleft, scalarright, s, namespaceRef);
		}
	}
	UsePart usePart = new UsePart(fullyQualifiedName, 
		new SimpleReference(aliasNameleft, aliasNameright, aliasName));
	List useDeclList = new LinkedList();
	useDeclList.add(usePart);
	parser.declarations.push(new UseStatement(startleft, endright, useDeclList));
:}

;

named_namespace_body ::=
T_SEMICOLON:end /* unbracketed syntax */
{:
	NamespaceDeclaration namespaceDeclaration = (NamespaceDeclaration)parser.declarations.pop();
	namespaceDeclaration.setEnd(endright);
	namespaceDeclaration.setBracketed(false);

	parser.currentNamespace = namespaceDeclaration;

	parser.metUnbracketedNSDecl = true;
	if (parser.metBracketedNSDecl) {
		parser.reportError(new ASTError(namespaceDeclaration.sourceStart(), endright), "Cannot mix bracketed namespace declarations with unbracketed namespace declarations");
	}
	
	RESULT = namespaceDeclaration;
:}
;




inner_statement_list ::=
inner_statement_list:statementList inner_statement:statement
{:
	// Ignore null statements
	if(statement != null) {
		statementList.add(statement);
		if(statement.getKind() == ASTNodeKinds.AST_ERROR){
			if(!parser.declarations.isEmpty()) {
				Statement node = parser.declarations.peek();
				if(node.sourceStart() == statement.sourceStart() && node.sourceEnd() == statement.sourceEnd()) {
					statementList.add(parser.declarations.pop());
				}
			}		
		}
	}
	RESULT = statementList;
:}

| /* empty */
{: 
	RESULT = new LinkedList(); 
:}
;

inner_statement ::=
statement:statement
{: 
	RESULT = statement; 
:}

| function_declaration_statement:statement
{: 
	RESULT = statement; 
:}

| class_declaration_statement:statement
{: 
	RESULT = statement; 
:}
;

statement ::=
unticked_statement:statement
{: 
	RESULT = statement; 
:}
| error:theError /* error statement */
{:
	parser.reportError();
	ASTError error = new ASTError(theErrorleft, theErrorright);
	RESULT = error;	
:}
;

unticked_statement ::=
T_CURLY_OPEN:token
{:
	Block block = new Block(tokenleft, tokenleft, new LinkedList());
	parser.declarations.push(block);
	
:}
inner_statement_list:statementList T_CURLY_CLOSE:end
{:
	Block block = (Block)parser.declarations.pop();
	block.setEnd(endright);
	block.getStatements().clear();
	block.acceptStatements(statementList);
	
	RESULT = block;
:}

| T_IF:token T_OPEN_PARENTHESE expr:condition T_CLOSE_PARENTHESE statement:iftrue elseif_list:elseif else_single:iffalse
{:
	Expression innerCondition = null;	
	Statement trueStatement = null;
	Statement falseStatement = iffalse;
		
	for (int i=0 ; i < elseif[0].size() ; i++) {
		innerCondition = (Expression)elseif[0].get(i);	
	 	trueStatement = (Statement)elseif[1].get(i);
	 	int start = ((Integer)elseif[2].get(i)).intValue();
		falseStatement = new IfStatement(start, iffalseright, innerCondition, trueStatement, falseStatement);
	}
	IfStatement ifStatement = new IfStatement(tokenleft, iffalseright, condition, iftrue, falseStatement);		
	
	RESULT = ifStatement;
:}

| T_IF:token T_OPEN_PARENTHESE expr:condition T_CLOSE_PARENTHESE T_NEKUDOTAIM:colon inner_statement_list:ifTrueStatementList new_elseif_list:elseif new_else_single:iffalse T_ENDIF T_SEMICOLON:end
{:
	Expression innerCondition = null;	
	Statement trueStatement = null;
	Statement falseStatement = iffalse;
		
	for (int i=0 ; i < elseif[0].size() ; i++) {
		innerCondition = (Expression)elseif[0].get(i);	
	 	trueStatement = (Statement)elseif[1].get(i);
	 	int start = ((Integer)elseif[2].get(i)).intValue();
		falseStatement = new IfStatement(start, iffalseright, innerCondition, trueStatement, falseStatement);
	}
	Block block = new Block(colonleft, ifTrueStatementListright, ifTrueStatementList);
	IfStatement ifStatement = new IfStatement(tokenleft, iffalseright, condition, block, falseStatement);		
	
	RESULT = ifStatement;
:}

| T_WHILE:token T_OPEN_PARENTHESE expr:expr T_CLOSE_PARENTHESE while_statement:statement
{:
	WhileStatement whileStatement = new WhileStatement(tokenleft, statementright, expr, statement);			
	RESULT = whileStatement;
:}

| T_DO:token statement:statement T_WHILE T_OPEN_PARENTHESE expr:expr T_CLOSE_PARENTHESE T_SEMICOLON:end
{:
	DoStatement doStatement = new DoStatement(tokenleft, endright, expr, statement);			
	RESULT = doStatement;
:}

| T_FOR:token T_OPEN_PARENTHESE for_expr:initializations T_SEMICOLON for_expr:conditions T_SEMICOLON for_expr:increasements T_CLOSE_PARENTHESE for_statement:statement
{:		
	ForStatement forStatement = new ForStatement(tokenleft, statementright, initializations, conditions, increasements, statement);			
	RESULT = forStatement;
:}

|  T_FOR:token T_OPEN_PARENTHESE for_expr:initializations T_CLOSE_PARENTHESE for_statement:statement
{:		
	ForStatement forStatement = new ForStatement(tokenleft, statementright, initializations, null, null, statement);			
	RESULT = forStatement;
:}

| T_SWITCH:token T_OPEN_PARENTHESE expr:expr T_CLOSE_PARENTHESE switch_case_list:caseBlock
{:
	SwitchStatement switchStatement = new SwitchStatement(tokenleft, caseBlockright, expr, caseBlock);
	RESULT = switchStatement;
:}

| T_BREAK:token T_SEMICOLON:end
{: 
	RESULT = new BreakStatement(tokenleft, endright); 
:}

| T_BREAK:token expr:expr T_SEMICOLON:end
{: 
	RESULT = new BreakStatement(tokenleft, endright, expr); 
:}

| T_CONTINUE:token T_SEMICOLON:end
{: 
	RESULT = new ContinueStatement(tokenleft, endright); 
:}

| T_CONTINUE:token expr:expr T_SEMICOLON:end
{: 
	RESULT = new ContinueStatement(tokenleft, endright, expr); 
:}

| T_RETURN:token T_SEMICOLON:end
{: 
	RESULT = new ReturnStatement(tokenleft, endright); 
:}

| T_RETURN:token expr_without_variable:expr T_SEMICOLON:end
{: 
	RESULT = new ReturnStatement(tokenleft, endright, expr); 
:}

| T_RETURN:token variable:expr T_SEMICOLON:end
{: 
	RESULT = new ReturnStatement(tokenleft, endright, expr); 
:}


| T_VAR:start static_var_list:list T_SEMICOLON:end
{:
	VarStatement s = new VarStatement(startleft, endright, list);
	RESULT = s;
:}
| T_INLINE_HTML

| expr:expr T_SEMICOLON:end
{: 
	ExpressionStatement expressionStatement = new ExpressionStatement(exprleft, endright, expr);
	RESULT = expressionStatement;
:}

| T_SEMICOLON:token /* empty statement */
{: 
	RESULT = new EmptyStatement(tokenleft, tokenright); 
:}

| T_TRY:start T_CURLY_OPEN:tryBlockStart inner_statement_list:tryList T_CURLY_CLOSE:tryBlockEnd
T_CATCH:catch_word T_OPEN_PARENTHESE tracked_variable:var T_CLOSE_PARENTHESE
T_CURLY_OPEN:catchBlockStart inner_statement_list:catchList T_CURLY_CLOSE:catchBlockEnd
additional_catches:catchesList
{:
	Block tryBlock = new Block(tryBlockStartleft, tryBlockEndright, tryList);
	Block catchBlock = new Block(catchBlockStartleft, catchBlockEndright, catchList);
	CatchClause catchClause = new CatchClause(catch_wordleft, catchBlockEndright, var, catchBlock);
	((LinkedList) catchesList).addFirst(catchClause);
	TryStatement tryStatement = new TryStatement(startleft, catchesListright, tryBlock, catchesList);
	RESULT = tryStatement;	
:}

| T_THROW:token expr:expr T_SEMICOLON:end
{: 
	RESULT = new ThrowStatement(tokenleft, endright, expr); 
:}

| T_GOTO:start T_STRING:label T_SEMICOLON:end
{:
	RESULT = new GotoStatement(startleft, endright, label);
:}
;

additional_catches ::=
non_empty_additional_catches:list
{:
	RESULT = list;
:}

| /* empty */
{:
	List list = new LinkedList();
	RESULT = list;	
:}
;

non_empty_additional_catches ::=
additional_catch:catch_statement
{:
	List list = new LinkedList();
	list.add(catch_statement);
	RESULT = list;	
:}
| non_empty_additional_catches:list additional_catch:catch_statement
{:
	list.add(catch_statement);
	RESULT = list;	
:}
;

additional_catch ::=
T_CATCH:catch_word T_OPEN_PARENTHESE  T_STRING:var T_CLOSE_PARENTHESE
 T_CURLY_OPEN:catchBlockStart inner_statement_list:catchList T_CURLY_CLOSE:catchBlockEnd
{:
	Block catchBlock = new Block(catchBlockStartleft, catchBlockEndright, catchList);
	VariableReference variable = new VariableReference(varleft, varright, var, PHPVariableKind.LOCAL);
	CatchClause catchClause = new CatchClause(catch_wordleft, catchBlockEndright,variable, catchBlock);
	RESULT = catchClause;
:}
;

unset_variables ::=
unset_variable:var
{:
	PHPCallArgumentsList list = new PHPCallArgumentsList();
	list.addNode(var);
	RESULT = list;
:}

| unset_variables:list T_COMMA unset_variable:var
{:
	list.addNode(var);
	RESULT = list;
:}
;

unset_variable ::=
variable:var
{:
	RESULT = var;
:}
;


function_declaration_statement ::=
unticked_function_declaration_statement:functionDeclaration
{:
	RESULT = functionDeclaration;
:}
;

class_declaration_statement ::=
unticked_class_declaration_statement:classDeclaration
{:
	RESULT = classDeclaration;
:}
;

is_reference ::=
/* empty */
{:
	RESULT = Boolean.FALSE;
:}
;

unticked_function_declaration_statement ::=
T_FUNCTION:start is_reference:isReference T_STRING:functionName
{:
	PHPMethodDeclaration functionDeclaration = new PHPMethodDeclaration(startleft, functionNameright, functionNameleft, functionNameright, functionName, 0, null, new Block(functionNameright,functionNameright,null), isReference.booleanValue(), start);
	parser.addDeclarationStatement(functionDeclaration);
	parser.declarations.push(functionDeclaration);
:}
T_OPEN_PARENTHESE parameter_list:paramList T_CLOSE_PARENTHESE:closeParenthese
{:
	PHPMethodDeclaration functionDeclaration = (PHPMethodDeclaration)parser.declarations.peek();
	functionDeclaration.acceptArguments(paramList);
	functionDeclaration.setEnd(closeParentheseright);
:}
function_body:body
{:
	RESULT = body;
:}
;

function_body ::=
T_CURLY_OPEN:blockStart inner_statement_list:statementList T_CURLY_CLOSE:blockEnd
{:
	PHPMethodDeclaration functionDeclaration = (PHPMethodDeclaration)parser.declarations.pop();
	Block block = functionDeclaration.getBody();
	block.setStart(blockStartleft);
	block.setEnd(blockEndright);
	block.getStatements().clear();
	block.acceptStatements(statementList);
	functionDeclaration.setEnd(blockEndright);
	RESULT = functionDeclaration;
:}
| error:theError
{:
	RESULT = (PHPMethodDeclaration)parser.declarations.pop();
:}
;

unticked_class_declaration_statement ::=
class_entry_type:modifier T_STRING:className
{:
	ClassDeclaration classDeclaration;
	classDeclaration = new ClassDeclaration(modifierleft ,classNameright, 
	classNameleft, classNameright, modifier.modifier, className, null, null, 
	new Block(classNameright,classNameright,null), modifier.doc);
	
	classDeclaration.setRecovered(true);
	parser.addDeclarationStatement(classDeclaration);
	parser.declarations.push(classDeclaration);
:}
extends_from:superClass errorOrNot implements_list:interfaces
{:
	ClassDeclaration classDeclaration = (ClassDeclaration)parser.declarations.peek();
	if (superClass != null) {
		classDeclaration.setSuperClass(superClass);
	}
	if (interfaces != null) {
		classDeclaration.setInterfaceList(interfaces);
	}
	classDeclaration.setEnd(interfacesright);
	classDeclaration.getBody().setStart(interfacesright);
	classDeclaration.getBody().setEnd(interfacesright);
:}
T_CURLY_OPEN:blockStart class_statement_list:statementList class_closure:blockEnd
{:
	if(blockEnd != null) {
		parser.reportError(new ASTError(statementListright - 1, statementListright), "syntax error, unfinished class declaration");
		parser.pendingStatement = blockEnd;
	}
	ClassDeclaration classDeclaration = (ClassDeclaration)parser.declarations.pop();
	classDeclaration.setRecovered(false);
	classDeclaration.setEnd(blockEndright);
	classDeclaration.getBody().setStart(blockStartleft);
	classDeclaration.getBody().setEnd(blockEndright);
	RESULT = classDeclaration;
:}
;

errorOrNot ::=
error
|
;

/* Here go all elements that trigger the class closure */
class_closure ::=
T_CURLY_CLOSE /* normal behaviour */

/* error recovery - function declaration closes current class */
/* XXX: This is disabled for now because of lambda functions
function_declaration_statement:statement 
{:
	RESULT = statement;
:}
*/

/* error recovery - another class declaration closes current class */
| class_declaration_statement:statement
{:
	RESULT = statement;
:}
;

class_entry_type ::=
T_CLASS:value
{:
	RESULT = parser.new ModifierDocPair(Modifiers.AccDefault, value); 
:}
;

extends_from ::=
/* empty */
{:
	RESULT = null;
:}
;

implements_list ::=
/* empty */
{:
	List list = new LinkedList();
	RESULT = list;
:}
;

for_statement ::=
statement:statement
{:
	RESULT = statement;
:}

| T_NEKUDOTAIM:start inner_statement_list:statementList T_ENDFOR T_SEMICOLON
{:
	Block block = new Block(startleft, statementListright, statementList);
	RESULT = block;
:}
;

switch_case_list ::=
T_CURLY_OPEN:start case_list:caseList T_CURLY_CLOSE:end
{:
	Block block = new Block(startleft, endright, caseList);	
	RESULT = block; 
:}

| T_CURLY_OPEN:start T_SEMICOLON case_list:caseList T_CURLY_CLOSE:end
{:
	Block block = new Block(startleft, endright, caseList);	
	RESULT = block; 
:}

| T_NEKUDOTAIM:start case_list:caseList T_ENDSWITCH T_SEMICOLON:end
{:
	Block block = new Block(startleft, endright, caseList);	
	RESULT = block; 
:}

| T_NEKUDOTAIM:start T_SEMICOLON case_list:caseList T_ENDSWITCH T_SEMICOLON:end
{:
	Block block = new Block(startleft, endright, caseList);	
	RESULT = block; 
:}
;

case_list ::=
/* empty */
{:
	RESULT = new LinkedList(); // of SwitchCase
:}

| case_list:caseList T_CASE:token expr:expr case_separator inner_statement_list:statements
{:
	SwitchCase switchCase = new SwitchCase(tokenleft, statementsright, expr, statements, false);
	if (caseList == null) {
		caseList = new LinkedList(); // of switchCase
	}
	caseList.add(switchCase);
	RESULT = caseList;
:}

| case_list:caseList T_DEFAULT:token case_separator inner_statement_list:statements
{:
	SwitchCase switchCase = new SwitchCase(tokenleft, statementsright, null, statements, true);
	if (caseList == null) {
		caseList = new LinkedList(); // of SwitchCase
	}
	caseList.add(switchCase);
	RESULT = caseList;
:}
;

/* Note: we don't capture seperator type */
case_separator ::=
T_NEKUDOTAIM 
| T_SEMICOLON
;

while_statement ::=
statement:statement
{:
	RESULT = statement;
:}

| T_NEKUDOTAIM:colon inner_statement_list:statementList T_ENDWHILE T_SEMICOLON
{:
	Block block = new Block(colonleft, statementListright, statementList);
	RESULT = block;
:}
;

elseif_list ::=
/* empty */
{:
	List listConditions = new LinkedList();
	List listStatements = new LinkedList();
	List listTokens = new LinkedList();
	
	List[] returnList = new List[] { listConditions, listStatements, listTokens };
	
	RESULT = returnList;
:}

| elseif_list:elseifList T_ELSEIF:token T_OPEN_PARENTHESE expr:condition T_CLOSE_PARENTHESE statement:iftrue
{:	
	((LinkedList)elseifList[0]).addFirst(condition);
	((LinkedList)elseifList[1]).addFirst(iftrue);
	((LinkedList)elseifList[2]).addFirst(new Integer(tokenleft));

	RESULT = elseifList;
:}
;

new_elseif_list ::=
/* empty */
{:
	List listConditions = new LinkedList();
	List listStatements = new LinkedList();
	List listTokens = new LinkedList();
	
	List[] returnList = new List[] { listConditions, listStatements, listTokens };
	
	RESULT = returnList;
:}

| new_elseif_list:elseifList T_ELSEIF:token T_OPEN_PARENTHESE expr:condition T_CLOSE_PARENTHESE T_NEKUDOTAIM:colon inner_statement_list:statementList
{:	
	Block block = new Block(colonleft, statementListright, statementList);
	((LinkedList)elseifList[0]).addFirst(condition);
	((LinkedList)elseifList[1]).addFirst(block);
	((LinkedList)elseifList[2]).addFirst(new Integer(tokenleft));

	RESULT = elseifList;
:}
;

else_single ::=
/* empty */
{:
	RESULT = null;
:}

| T_ELSE statement:statement
{:
	RESULT = statement;
:}
;

new_else_single ::=
/* empty */
{:
	RESULT = null;
:}

| T_ELSE T_NEKUDOTAIM:colon inner_statement_list:statementList
{:
	Block block = new Block(colonleft, statementListright, statementList);
	RESULT = block;
:}
;

parameter_list ::=
non_empty_parameter_list:list
{:
	RESULT = list;
:}

| /* empty */
{:
	List list = new LinkedList();
	RESULT = list;
:}
;

non_empty_parameter_list ::=
parameter:parameter
{:
	List list = new LinkedList();
	if(parameter != null) {
		list.add(parameter);
	}
	RESULT = list;
:}

| non_empty_parameter_list:list T_COMMA parameter:parameter
{:
	if(parameter != null) {
		list.add(parameter);
	}
	RESULT = list;
:}
| non_empty_parameter_list:list T_COMMA:comma /* error recovery */
{:
	parser.reportError(new ASTError(commaleft, commaright), "syntax error, unexpected ','");
	RESULT = list;
:}
;

parameter ::=
optional_class_type:classType T_STRING:var
{:
	int start = classType == null ? varleft : classTypeleft;
	VariableReference v = new VariableReference(varleft, varright, var, PHPVariableKind.LOCAL);
	FormalParameter parameter = new FormalParameter(start, varright, classType, v);
	RESULT = parameter;	
:}

| optional_class_type:classType T_STRING:var T_EQUAL static_scalar:scalar
{:
	int start = classType == null ? varleft : classTypeleft;
	VariableReference v = new VariableReference(varleft, varright, var, PHPVariableKind.LOCAL);
	FormalParameter parameter = new FormalParameter(start, scalarright, classType, v, scalar);
	RESULT = parameter;	
:}


| error:theError
{:
	parser.reportError(new ASTError(theErrorleft, theErrorright));
	RESULT = null;	
:}
;

optional_class_type ::=
/* empty */
{:
	RESULT = null;
:}
;

function_call_parameter_list ::=
non_empty_function_call_parameter_list:paramsList
{:
	RESULT = paramsList;
:}

| /* empty */
{:
	PHPCallArgumentsList list = new PHPCallArgumentsList();
	RESULT = list;
:}
;

non_empty_function_call_parameter_list ::=
expr_without_variable:var
{:
	PHPCallArgumentsList paramsList = new PHPCallArgumentsList();
	paramsList.addNode(var);	
	RESULT = paramsList;
:}

| variable:var
{:
	PHPCallArgumentsList paramsList = new PHPCallArgumentsList();
	paramsList.addNode(var);	
	RESULT = paramsList;
:}

| non_empty_function_call_parameter_list:paramsList T_COMMA expr_without_variable:var
{:
	paramsList.addNode(var);
	RESULT = paramsList;
:}

| non_empty_function_call_parameter_list:paramsList T_COMMA variable:var
{:
	paramsList.addNode(var);	
	RESULT = paramsList;
:}
| T_CURLY_OPEN:start object_pair_list:list T_CURLY_CLOSE:end
{:
	Expression expr = new ArrayCreation(startleft, endright, list);
	PHPCallArgumentsList paramsList = new PHPCallArgumentsList();
	paramsList.addNode(expr);
	RESULT = paramsList;
:}
| non_empty_function_call_parameter_list:nlist T_COMMA T_CURLY_OPEN:start object_pair_list:list T_CURLY_CLOSE:end
{:
		Expression expr = new ArrayCreation(nlistleft, endright, list);
		nlist.addNode(expr);
		RESULT = nlist; 
:}
;



static_var_list ::=
static_var_list:list T_COMMA T_STRING:var
{:
	VariableReference v = new VariableReference(varleft, varright, var); 
	list.add(v);
	RESULT = list;
:}

| static_var_list:list T_COMMA T_STRING:var T_EQUAL var_expr:expr
{:
	VariableReference v = new VariableReference(varleft, varright, var); 
	Assignment assignment = new Assignment(varleft, exprright, v, Assignment.OP_EQUAL, expr); 
	list.add(assignment);
	RESULT = list;
:}

| T_STRING:var
{:
	VariableReference v = new VariableReference(varleft, varright, var); 
	List list = new LinkedList();
	list.add(v);
	RESULT = list;
:}

| T_STRING:var T_EQUAL var_expr:expr
{:
	VariableReference v = new VariableReference(varleft, varright, var); 
	Assignment assignment = new Assignment(varleft, exprright, v, Assignment.OP_EQUAL, expr); 
	List list = new LinkedList();
	list.add(assignment);
	RESULT = list;
:}	
;

class_statement_list ::=
class_statement_list:list class_statement:classStatement
{:
	if(!(parser.declarations.peek() instanceof TypeDeclaration)) {
		parser.declarations.pop();
	}
:}
| /* empty */
;

class_statement ::=
variable_modifiers:modifier class_variable_declaration:decList T_SEMICOLON
{:
	Iterator i = decList.iterator();
	while (i.hasNext()) {
		ASTNode[] decl = (ASTNode[]) i.next();
		VariableReference variable = (VariableReference)decl[0];
		Expression initializer = (Expression)decl[1];
		int start = variable.sourceStart();
		int end = (initializer == null ? variable.sourceEnd() : initializer.sourceEnd());
		parser.addDeclarationStatement(new PHPFieldDeclaration(variable, initializer, start, end, modifier.modifier, modifierleft, modifier.doc));
	}
:}

| constant_declaration:decList T_SEMICOLON
{:
	Iterator i = decList.iterator();
	while (i.hasNext()) {
		ASTNode[] decl = (ASTNode[]) i.next();
		ConstantReference constant = (ConstantReference)decl[0];
		Expression initializer = (Expression)decl[1];
		
		PHPDocBlock docBlock = null;
		if (decl.length == 3) {
			docBlock = (PHPDocBlock)decl[2];
		}
		int start = constant.sourceStart();
		int end = (initializer == null ? constant.sourceEnd() : initializer.sourceEnd());
		parser.addDeclarationStatement(new ConstantDeclaration(constant, initializer, decListleft, end, docBlock));
	}
:}

| method_modifiers:modifier T_FUNCTION:start is_reference:isReference string_st:functionName
{:
	int methodStart = modifier == null ? startleft : modifierleft;
	int modifierValue = modifier == null ? Modifiers.AccPublic : modifier.modifier;
	PHPDocBlock docBlock = start;
	if (modifier != null && modifier.doc != null) {
		docBlock = modifier.doc;
	}
	PHPMethodDeclaration methodDeclaration = new PHPMethodDeclaration(methodStart, functionNameright, functionNameleft, functionNameright, functionName, modifierValue, null, new Block(functionNameright, functionNameright, null), isReference.booleanValue(), docBlock);
	parser.addDeclarationStatement(methodDeclaration);
	parser.declarations.push(methodDeclaration);
:}
T_OPEN_PARENTHESE parameter_list:paramList T_CLOSE_PARENTHESE:closeParenthese
{:
	PHPMethodDeclaration functionDeclaration = (PHPMethodDeclaration)parser.declarations.peek();
	functionDeclaration.acceptArguments(paramList);
	functionDeclaration.setEnd(closeParentheseright);
:}
method_body:body
{:
	PHPMethodDeclaration methodDeclaration = (PHPMethodDeclaration)parser.declarations.pop();
	if(body instanceof ASTError) {
		parser.reportError(new ASTError(methodDeclaration.sourceEnd() - 1, methodDeclaration.sourceEnd()), "syntax error, unfinished method declaration");
	}
	TypeDeclaration type = (TypeDeclaration)parser.declarations.peek();
	methodDeclaration.setDeclaringTypeName(type.getName());
:}
;

variable_modifiers ::=
{:
	RESULT = null;
:}
;




method_body ::=
T_SEMICOLON:end /* abstract method */
{:
	PHPMethodDeclaration methodDeclaration = (PHPMethodDeclaration)parser.declarations.peek();
	methodDeclaration.getBody().setStart(endleft);
	methodDeclaration.getBody().setEnd(endright);
	methodDeclaration.setEnd(endright);
	RESULT = null;
:}
| T_CURLY_OPEN:start inner_statement_list:statementList T_CURLY_CLOSE:end
{:
	PHPMethodDeclaration methodDeclaration = (PHPMethodDeclaration)parser.declarations.peek();
	methodDeclaration.getBody().setStart(startleft);
	methodDeclaration.getBody().setEnd(endright);
	methodDeclaration.getBody().getStatements().clear();
	methodDeclaration.getBody().acceptStatements(statementList);
	methodDeclaration.setEnd(endright);
	RESULT = null;
:}
| /* error recovery */
{:
	parser.reportError();
	RESULT = new ASTError(0,0);
:}
;

method_modifiers ::=
/* empty */
{:
	RESULT = null;
:}
;

class_variable_declaration ::=
class_variable_declaration:list T_COMMA T_VARIABLE:var
{:
	VariableReference varId = new VariableReference(varleft, varright, var);
	list.add(new ASTNode[] {varId, null});
	RESULT = list;
:}

| class_variable_declaration:list T_COMMA T_VARIABLE:var T_EQUAL static_scalar:expr
{:
	VariableReference varId = new VariableReference(varleft, varright, var);
	list.add(new ASTNode[] {varId, expr});
	RESULT = list;
:}

| T_VARIABLE:var
{:
	List list = new LinkedList();
	VariableReference varId = new VariableReference(varleft, varright, var);
	list.add(new ASTNode[] {varId, null});
	RESULT = list;
:}

| T_VARIABLE:var T_EQUAL static_scalar:expr
{:
	List list = new LinkedList();
	VariableReference varId = new VariableReference(varleft, varright, var);
	list.add(new ASTNode[] {varId, expr});
	RESULT = list;
:}
;

instance_call ::=
/* empty */
{:
	RESULT = null;
:}
;

non_empty_for_expr ::=
non_empty_for_expr:exprList T_COMMA expr:expr
{:
	exprList.add(expr);
	RESULT = exprList;
:}

| expr:expr
{:
	List exprList = new LinkedList();
	exprList.add(expr);
	RESULT = exprList;
:}

| T_VAR static_var_list:list
{:
	RESULT = list;
:}

| T_VAR T_STRING T_IN expr:expr
{:
	List exprList = new LinkedList();
	exprList.add(expr);
	RESULT = exprList;
:}
;

constant_declaration ::=
constant_declaration:list T_COMMA T_STRING:constName T_EQUAL static_scalar:expr
{:
	ConstantReference constId = new ConstantReference(constNameleft, constNameright, constName);
	list.add(new ASTNode[] {constId, expr});
	RESULT = list;
:}

| T_CONST:value T_STRING:constName T_EQUAL static_scalar:expr
{:
	List list = new LinkedList();
	ConstantReference constId = new ConstantReference(constNameleft, constNameright, constName);
	list.add(new ASTNode[] {constId, expr, value});
	RESULT = list;
:}
;

for_expr ::=
/* empty */
{:
	RESULT = new LinkedList();
:}

| non_empty_for_expr:exprList
{:
	RESULT = exprList;
:}	
;

new_expr ::=
T_NEW:start class_name_reference:className ctor_arguments:ctor
{:
	if (ctor.sourceStart() == 0) {
		ctor.setStart(classNameright);
		ctor.setEnd(classNameright);
	}
	ClassInstanceCreation classInstanceCreation = new ClassInstanceCreation(startleft, ctorright, className, ctor);
	RESULT = classInstanceCreation;
:}
;

expr_without_variable ::=
T_LIST:start T_OPEN_PARENTHESE assignment_list:varList T_CLOSE_PARENTHESE:close T_EQUAL expr:expr
{:
	ListVariable vars = new ListVariable(startleft, closeright, varList);
	Assignment list = new Assignment(startleft, exprright, vars, Assignment.OP_EQUAL, expr);
	RESULT = list; 
:}

| variable:var T_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var, Assignment.OP_EQUAL, expr); 
:}

| variable:var T_EQUAL T_REFERENCE:reftoken variable:refvar
{: 
	RESULT = new Assignment(varleft, refvarright, var, Assignment.OP_REF_EQUAL, refvar); 
:}

| variable:var T_PLUS_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_PLUS_EQUAL, expr); 
:}

| variable:var T_MINUS_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_MINUS_EQUAL, expr); 
:}

| variable:var T_MUL_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_MUL_EQUAL, expr); 
:}

| variable:var T_DIV_EQUAL expr:expr
{: 	
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_DIV_EQUAL, expr); 
:}

| variable:var T_CONCAT_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_CONCAT_EQUAL, expr); 
:}

| variable:var T_MOD_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_MOD_EQUAL, expr); 
:}

| variable:var T_AND_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_AND_EQUAL, expr); 
:}

| variable:var T_OR_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_OR_EQUAL, expr); 
:}

| variable:var T_XOR_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_XOR_EQUAL, expr); 
:}

| variable:var T_SL_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_SL_EQUAL, expr); 
:}

| variable:var T_SR_EQUAL expr:expr
{: 
	RESULT = new Assignment(varleft, exprright, var , Assignment.OP_SR_EQUAL, expr); 
:}

| rw_variable:var T_INC:token
{: 
	RESULT = new PostfixExpression(varleft, tokenright, var , PostfixExpression.OP_INC); 
:} 

| T_INC:token rw_variable:var
{: 
	RESULT = new PrefixExpression(tokenleft, varright, var , PrefixExpression.OP_INC); 
:}
 
| rw_variable:var T_DEC:token
{: 
	RESULT = new PostfixExpression(varleft, tokenright, var , PostfixExpression.OP_DEC); 
:}
 
| T_DEC:token rw_variable:var
{: 
	RESULT = new PrefixExpression(tokenleft, varright, var , PrefixExpression.OP_DEC); 
:} 

| expr:expr1 T_BOOLEAN_OR expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_BOOL_OR, expr2); 
:}

| expr:expr1 T_BOOLEAN_AND expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_BOOL_AND, expr2); 
:}

| expr:expr1 T_LOGICAL_OR expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_STRING_OR, expr2); 
:}

| expr:expr1 T_LOGICAL_AND expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_STRING_AND, expr2); 
:}

| expr:expr1 T_LOGICAL_XOR expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_STRING_XOR, expr2);
:}

| expr:expr1 T_OR expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_OR, expr2); 
:}

| expr:expr1 T_REFERENCE expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_AND, expr2); 
:}

| expr:expr1 T_KOVA expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_XOR, expr2); 
:}

| expr:expr1 T_PLUS expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_PLUS, expr2); 
:}

| expr:expr1 T_MINUS expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_MINUS, expr2); 
:}

| expr:expr1 T_TIMES expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_MUL, expr2); 
:}

| expr:expr1 T_DIV expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_DIV, expr2); 
:}

| expr:expr1 T_PRECENT expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_MOD, expr2); 
:}

| expr:expr1 T_SL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_SL, expr2); 
:}

| expr:expr1 T_SR expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_SR, expr2); 
:}

| T_PLUS:token expr:expr
{: 
	RESULT = new UnaryOperation(tokenleft, exprright, expr , UnaryOperation.OP_PLUS); 
:}

| T_MINUS:token expr:expr
{: 
	RESULT = new UnaryOperation(tokenleft, exprright, expr , UnaryOperation.OP_MINUS); 
:}

| T_NOT:token expr:expr
{: 
	RESULT = new UnaryOperation(tokenleft, exprright, expr , UnaryOperation.OP_NOT); 
:}

| T_TILDA:token expr:expr
{: 
	RESULT = new UnaryOperation(tokenleft, exprright, expr , UnaryOperation.OP_TILDA); 
:}

| expr:expr1 T_IS_IDENTICAL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_IS_IDENTICAL, expr2); 
:}

| expr:expr1 T_IS_NOT_IDENTICAL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_IS_NOT_IDENTICAL, expr2); 
:}

| expr:expr1 T_IS_EQUAL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_IS_EQUAL, expr2); 
:}

| expr:expr1 T_IS_NOT_EQUAL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_IS_NOT_EQUAL, expr2); 
:}

| expr:expr1 T_RGREATER expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_RGREATER, expr2); 
:}

| expr:expr1 T_IS_SMALLER_OR_EQUAL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_IS_SMALLER_OR_EQUAL, expr2); 
:}

| expr:expr1 T_LGREATER expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_LGREATER, expr2); 
:}

| expr:expr1 T_IS_GREATER_OR_EQUAL expr:expr2
{: 
	RESULT = new InfixExpression(expr1left, expr2right, expr1 , InfixExpression.OP_IS_GREATER_OR_EQUAL, expr2); 
:}


| T_OPEN_PARENTHESE:start expr:expr T_CLOSE_PARENTHESE:end
{:
	RESULT = expr; 
:}

| new_expr:expr
{:
	RESULT = expr; 
:}

| T_OPEN_PARENTHESE:start new_expr:expr T_CLOSE_PARENTHESE:end instance_call:call
{:
	expr.setChainingInstanceCall(call);
	
	if (call.getChainingMethodPropertyList() != null
		&& !call.getChainingMethodPropertyList()
			.getChilds().isEmpty()) {
		// then get the aggregated list of properties (->...->...->...)
		List list = call.getChainingMethodPropertyList()
			.getChilds();
		
		// now create the dispatch(es) nodes 
		Expression dispatcher = expr;
	
		Iterator listIt = list.iterator();
		while (listIt.hasNext()) {
			Expression property = (Expression)listIt.next();
			dispatcher = parser.createDispatch(dispatcher, property);
		}	
		RESULT = dispatcher;
	}else{
		RESULT = expr; 
	}

	
	
:}

| expr:condition T_QUESTION_MARK expr:ifTrue T_NEKUDOTAIM expr:ifFalse
{: 
	RESULT = new ConditionalExpression(conditionleft, ifFalseright, condition , ifTrue, ifFalse); 
:}

| expr:condition T_QUESTION_MARK T_NEKUDOTAIM expr:ifFalse
{: 
	RESULT = new ConditionalExpression(conditionleft, ifFalseright, condition , null, ifFalse); 
:}

| internal_functions_in_yacc:expr
{:
	RESULT = expr;
:}

| T_INT_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_INT); 
:}

| T_DOUBLE_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_REAL); 
:}

| T_STRING_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_STRING); 
:}

| T_ARRAY_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_ARRAY); 
:}

| T_OBJECT_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_OBJECT); 
:}

| T_BOOL_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_BOOL); 
:}

| T_UNSET_CAST:token expr:expr
{: 
	RESULT = new CastExpression(tokenleft, exprright, expr , CastExpression.TYPE_UNSET); 
:}

| T_AT:start expr:expr 
{:
	IgnoreError ignoreError = new IgnoreError(startleft, exprright, expr);
	RESULT = ignoreError;
:}

| scalar:scalar
{: 
	RESULT = scalar; 
:}

| T_ARRAY:start T_OPEN_PARENTHESE array_pair_list:list T_CLOSE_PARENTHESE:end
{:
	Expression expr = new ArrayCreation(startleft, endright, list);
	RESULT = expr;
:}

| T_OPEN_RECT:start array_pair_list:list T_CLOSE_RECT:end
{: 
	Expression expr = new ArrayCreation(startleft, endright, list);
	RESULT = expr;
:}

| T_BACKQUATE:start backticks_expr:list T_BACKQUATE:end
{:
	BackTickExpression backTickExpression = new BackTickExpression(startleft, endright, list);
	RESULT = backTickExpression;
:}

| T_PRINT:start T_OPEN_PARENTHESE var_expr:expr T_CLOSE_PARENTHESE
{:
	PHPCallArgumentsList list = new PHPCallArgumentsList();
	if (expr != null) {
		list.addNode(expr);
		list.setStart(expr.sourceStart());
		list.setEnd(expr.sourceEnd());
	} else {
		list.setStart(startright);
		list.setEnd(startright);
	}
	SimpleReference name = new SimpleReference(startleft, startright, "print");
	PHPCallExpression result = new PHPCallExpression(startleft, exprright, null, name, list);
	RESULT = result;
:}

| T_FUNCTION:s is_reference:isReference 
T_OPEN_PARENTHESE parameter_list:paramList T_CLOSE_PARENTHESE lexical_vars:varsList
T_CURLY_OPEN:blockStart inner_statement_list:list T_CURLY_CLOSE:blockEnd
{:
	RESULT = new LambdaFunctionDeclaration(sleft, blockEndright, paramList, varsList, 
		new Block(blockStartleft, blockEndright, list), isReference.booleanValue());
:}
| T_STATIC T_FUNCTION:s is_reference:isReference
T_OPEN_PARENTHESE parameter_list:paramList T_CLOSE_PARENTHESE lexical_vars:varsList
T_CURLY_OPEN:blockStart inner_statement_list:list T_CURLY_CLOSE:blockEnd
{:
	RESULT = new LambdaFunctionDeclaration(sleft, blockEndright, paramList, varsList, 
		new Block(blockStartleft, blockEndright, list), isReference.booleanValue(),true);
:}

;

lexical_vars ::=
/* empty */
{:
	RESULT = null;
:}
;


function_call ::=
variable_without_objects:reflectionName T_OPEN_PARENTHESE:start function_call_parameter_list:parameters T_CLOSE_PARENTHESE:end
{:
	parameters.setStart(startright);
	parameters.setEnd(endleft);
	RESULT = new ReflectionCallExpression(reflectionNameleft, endright, null, reflectionName, parameters); 
:}
;

class_name ::=
T_STATIC:s
{:
	RESULT = new FullyQualifiedReference(sleft, sright, "static", null);
:}

| namespace_name:name
{:
	RESULT = name;
:}


| T_ARRAY:s
{:
	RESULT = new FullyQualifiedReference(sleft, sright, "Array", null);
:}
;

class_name_reference ::=
class_name:className
{:
	RESULT = className;
:}
;

dynamic_class_name_reference ::=
base_variable:var T_OBJECT_OPERATOR object_property:firstVarProperty dynamic_class_name_variable_properties:propertyList
{:
	// then get the aggregated list of properties (->...->...->...)
	LinkedList list = (LinkedList) propertyList;
	list.addFirst(firstVarProperty);
	
	// now create the dispatch(es) nodes 
	Expression dispatcher = (Expression)var;

	Iterator listIt = list.iterator();
	while (listIt.hasNext()) {
		Expression property = (Expression)listIt.next();
		dispatcher = parser.createDispatch(dispatcher, property);
	}	
	
	RESULT = dispatcher;
:}
;


backticks_expr ::=
/* empty */
{:
	RESULT = new LinkedList();
:}

| T_ENCAPSED_AND_WHITESPACE:string
{:
	List list = new LinkedList();
	Scalar scalar = new Scalar(stringleft, stringright, string, string == null ? Scalar.TYPE_UNKNOWN : Scalar.TYPE_STRING);
	list.add(scalar);
	RESULT = list;
:}

| encaps_list:list
{:
	RESULT = list;
:}
;

ctor_arguments ::=
/* empty */
{:
	RESULT = new PHPCallArgumentsList();
:}

| T_OPEN_PARENTHESE:start function_call_parameter_list:paramsList T_CLOSE_PARENTHESE:end
{:
	paramsList.setStart(startright);
	paramsList.setEnd(endleft);
	RESULT = paramsList;
:}
;

common_scalar ::=
T_LNUMBER:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, scalar, Scalar.TYPE_INT);
	RESULT = s;
:}

| T_DNUMBER:scalar
{: 
	Scalar s = new Scalar(scalarleft, scalarright, scalar, Scalar.TYPE_REAL);
	RESULT = s;
:}

| T_BNUMBER:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, scalar, Scalar.TYPE_BIN);
	RESULT = s;
:}
| T_CONSTANT_ENCAPSED_STRING:scalar
{: 
	Scalar s = new Scalar(scalarleft, scalarright, scalar, Scalar.TYPE_STRING);
	RESULT = s;
:}

| T_LINE:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__LINE__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_FILE:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__FILE__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_DIR:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__DIR__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_CLASS_C:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__CLASS__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_TRAIT_C:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__TRAIT__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_METHOD_C:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__METHOD__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_FUNC_C:scalar
{:
	Scalar s = new Scalar(scalarleft, scalarright, "__FUNCTION__", Scalar.TYPE_SYSTEM);
	RESULT = s;
:}

| T_NS_C:scalar
{:
	RESULT = new Scalar(scalarleft, scalarright, "__NAMESPACE__", Scalar.TYPE_SYSTEM);
:}

| T_START_HEREDOC:label T_ENCAPSED_AND_WHITESPACE:string T_END_HEREDOC:e
{:
	List list = new LinkedList();
	list.add(new Scalar(stringleft, stringright, string, string == null ? Scalar.TYPE_UNKNOWN : Scalar.TYPE_STRING));
	RESULT = new Quote(labelleft, eright, list, label.charAt(0) == '\'' ? Quote.QT_NOWDOC : Quote.QT_HEREDOC);
:}

| T_START_HEREDOC:label T_END_HEREDOC:e
{:
	RESULT = new Quote(labelleft, eright, new LinkedList(), label.charAt(0) == '\'' ? Quote.QT_NOWDOC : Quote.QT_HEREDOC);
:}

;

static_scalar ::=  /* compile-time evaluated scalars */
common_scalar:scalar
{:
	RESULT = scalar;
:}
| namespace_name:name
{:
	if (name.getNamespace() == null) {
		RESULT = new Scalar(nameleft, nameright, name.getName(), Scalar.TYPE_STRING);
	} else {
		RESULT = name;
	}
:}

| T_PLUS:start static_scalar:expr
{:
	UnaryOperation op = new UnaryOperation(startleft, exprright, expr, UnaryOperation.OP_PLUS);
	RESULT = op;	
:}

| T_MINUS:start static_scalar:expr
{:
	UnaryOperation op = new UnaryOperation(startleft, exprright, expr, UnaryOperation.OP_MINUS);
	RESULT = op;	
:}

| T_ARRAY:start T_OPEN_PARENTHESE static_array_pair_list:list T_CLOSE_PARENTHESE:end
{:
	ArrayCreation array = new ArrayCreation(startleft, endright, list);
	RESULT = array;	
:}

| T_OPEN_RECT:start static_array_pair_list:list T_CLOSE_RECT:end
{:
	ArrayCreation array = new ArrayCreation(startleft, endright, list);
	RESULT = array;	
:}

| static_class_constant:classConstant
{:
	RESULT = classConstant;
:}
;

static_class_constant ::=
class_name:className T_PAAMAYIM_NEKUDOTAYIM T_STRING:varName
{:
	ConstantReference vname = new ConstantReference(varNameleft, varNameright, varName);
	StaticConstantAccess constant = new StaticConstantAccess(classNameleft, varNameright, className, vname); 
	RESULT = constant;
:}
;

scalar ::=
T_STRING_VARNAME:scalar
{:
	// TODO: check if this is a scalar
	Scalar s = new Scalar(scalarleft, scalarright, scalar, Scalar.TYPE_STRING);
	RESULT = s;
:}

| common_scalar:scalar
{:
	RESULT = scalar;
:}

| T_START_HEREDOC:start encaps_list:list T_END_HEREDOC:end
{:
	Quote hereDoc = new Quote(startleft, endright, list, Quote.QT_HEREDOC);
	RESULT = hereDoc;
:}
;

static_array_pair_list ::=
/* empty */
{:
	List list = new LinkedList();
	RESULT = list;
:}

| non_empty_static_array_pair_list:list possible_comma
{:
	RESULT = list;
:}
;

/* do nothing */
possible_comma ::=
/* empty */
| T_COMMA
;

non_empty_static_array_pair_list ::=
non_empty_static_array_pair_list:list T_COMMA static_scalar:key T_DOUBLE_ARROW static_scalar:value
{:
	ArrayElement element = new ArrayElement(keyleft, valueright, key, value);
	list.add(element);
	RESULT = list;
:}

| non_empty_static_array_pair_list:list T_COMMA static_scalar:value
{:
	ArrayElement element = new ArrayElement(valueleft, valueright, value);
	list.add(element);
	RESULT = list;
:}

| static_scalar:key T_DOUBLE_ARROW static_scalar:value
{:
	List list = new LinkedList();
	ArrayElement element = new ArrayElement(keyleft, valueright, key, value);
	list.add(element);
	RESULT = list;
:}

| static_scalar:value
{:
	List list = new LinkedList();
	ArrayElement element = new ArrayElement(valueleft, valueright, value);
	list.add(element);
	RESULT = list;
:}
;

nekudotaim_expr ::=
variable:var T_NEKUDOTAIM expr:expr
{:
	List list = new LinkedList();
	Assignment assignment = new Assignment(varleft, exprright, var, Assignment.OP_NEKUDOTAIM, expr);
	list.add(assignment);
	RESULT = list;
:}

| nekudotaim_expr:list T_COMMA variable:var T_NEKUDOTAIM expr:expr
{:
		Assignment assignment = new Assignment(varleft, exprright, var, Assignment.OP_NEKUDOTAIM, expr);
		list.add(assignment);
		RESULT = list;
:}
;


var_expr ::=
expr:expr
{:
	RESULT = expr;
:}

| T_CURLY_OPEN:start object_pair_list:list T_CURLY_CLOSE:end
{:
	Expression expr = new ArrayCreation(startleft, endright, list);
	RESULT = expr;
:}
;

expr ::=
r_variable:var
{: RESULT = var; :}

| expr_without_variable:ewv
{: RESULT = ewv; :}
;

r_variable ::=
variable:var
{: RESULT = var; :}
;

w_variable ::=
variable:var
{: RESULT = var; :}
;

rw_variable ::=
variable:var
{: RESULT = var; :}
;

variable ::=
base_variable_with_function_calls:var T_OBJECT_OPERATOR object_property:memberProperty method_or_not:paramsList variable_properties:propertyList
{:
	// get the last property 
	Expression firstVarProperty = null;
	if (paramsList == null) {
		firstVarProperty = memberProperty;
	} else {
		if (memberProperty.getClass().equals(SimpleReference.class)) {
			firstVarProperty = new PHPCallExpression(memberPropertyleft, paramsListright, null, (SimpleReference)memberProperty, paramsList);
		} else {
			firstVarProperty = new ReflectionCallExpression(memberPropertyleft, paramsListright, null, memberProperty, paramsList);
		}
	}

	// then get the aggregated list of properties (->...->...->...)
	LinkedList list = (LinkedList) propertyList;
	list.addFirst(firstVarProperty);
	
	// now create the dispatch(es) nodes 
	Expression dispatcher = var;
	
	Iterator listIt = list.iterator();
	while (listIt.hasNext()) {
		Expression property = (Expression)listIt.next();
		dispatcher = parser.createDispatch(dispatcher, property);
	}

	RESULT = dispatcher;
:}

| base_variable_with_function_calls:var
{: 
	RESULT = var; 
:}
;

variable_properties ::=
variable_properties:variables variable_property:variableProperty
{:
	variables.add(variableProperty);
	RESULT = variables;	
:}

| /* empty */
{:
	RESULT = new LinkedList();
:}
;

variable_property ::=
T_OBJECT_OPERATOR object_property:memberProperty method_or_not:paramsList
{:
	Expression result = null;
	if (paramsList == null) {
		result = memberProperty;
	} else {
		if (memberProperty.getClass().equals(SimpleReference.class)) {
			result = new PHPCallExpression(memberPropertyleft, paramsListright, null, (SimpleReference)memberProperty, paramsList);
		} else {
			result = new ReflectionCallExpression(memberPropertyleft, paramsListright, null, memberProperty, paramsList);
		}
	}
	RESULT = result;
:}
;

method ::=
T_OPEN_PARENTHESE:start function_call_parameter_list:paramsList T_CLOSE_PARENTHESE:end
{:
	paramsList.setStart(startright);
	paramsList.setEnd(endleft);
	RESULT = paramsList;	
:}
;

array_method_dereference ::=
array_method_dereference:dereference T_OPEN_RECT:start dim_offset:index T_CLOSE_RECT:end
{:
	DereferenceNode var = new DereferenceNode(index,startleft, endright);
	dereference.getArrayDereferenceList().addNode(var);
	RESULT = dereference;
:}

|method:method T_OPEN_RECT:start dim_offset:index T_CLOSE_RECT:end
{:
	PHPArrayDereferenceList arrayDereferenceList = new PHPArrayDereferenceList(method);
	method.setArrayDereferenceList(arrayDereferenceList);
	DereferenceNode var = new DereferenceNode( index,startleft, endright);
	arrayDereferenceList.addNode(var);
	RESULT = method;
:}
;


method_or_not ::=
array_method_dereference:dereference
{:
	//RESULT = (PHPCallArgumentsList)dereference.getParent();
	RESULT = dereference;
:}

|method:method
{:
	RESULT = method;	
:}

| /* empty */
{:
	RESULT = null;
:}
;

variable_without_objects ::=
reference_variable:var
{: 
	RESULT = var; 
:}

| simple_indirect_reference:ref_count reference_variable:var
{:
	// the ref_count counts the number of reflection (DOLLAR sign) so now we should 
	// accomulate the dolars into reflection variables
	Expression finalVar = var;
	for (int i=0; i<ref_count.intValue(); i++) {
		finalVar = new ReflectionVariableReference(ref_countright - i - 1, varright, finalVar);				
	}
	RESULT = finalVar;
:}
;

static_member ::=
class_name:className T_PAAMAYIM_NEKUDOTAYIM variable_without_objects:var
{:
	StaticFieldAccess staticFieldAccess = new StaticFieldAccess(classNameleft, varright, className, var);
	RESULT = staticFieldAccess;
:}
;

variable_class_name ::=
reference_variable:var
{:
	RESULT = var;
:}
;

base_variable_with_function_calls ::=
base_variable:var
{: RESULT = var; :}

| function_call:var
{: RESULT = var; :}
;

base_variable ::=
reference_variable:var
{: 
	RESULT = var; 
:}

| simple_indirect_reference:ref_count reference_variable:var
{:
	// the ref_count counts the number of reflection (DOLLAR sign) so now we should 
	// accomulate the dolars into reflection variables
	Expression finalVar = var;
	for (int i=0; i<ref_count.intValue(); i++) {
		finalVar = new ReflectionVariableReference(ref_countright - i - 1, varright, finalVar);				
	}
	RESULT = finalVar;
:}

/*| static_member:staticFieldAccess
{:
	RESULT = staticFieldAccess;
:}*/
;

reference_variable ::=
reference_variable:varName T_OPEN_RECT dim_offset:index T_CLOSE_RECT:end
{:
	Expression var;
	if(varName.getKind() == ExpressionConstants.E_IDENTIFIER) { // VariableReference - $a
		var = new ArrayVariableReference(varNameleft, endright, ((SimpleReference)varName).getName(), index, ArrayVariableReference.VARIABLE_ARRAY);
	} else {
		var = new ReflectionArrayVariableReference(varNameleft, endright, varName, index, ReflectionArrayVariableReference.VARIABLE_ARRAY);
	}
	RESULT = var;
:}

| reference_variable:varName T_CURLY_OPEN expr:index T_CURLY_CLOSE:end
{:
	Expression var;
	if(varName.getKind() == ExpressionConstants.E_IDENTIFIER) { // VariableReference - $a
		var = new ArrayVariableReference(varNameleft, endright, ((SimpleReference)varName).getName(), index, ArrayVariableReference.VARIABLE_HASHTABLE);
	} else {
		var = new ReflectionArrayVariableReference(varNameleft, endright, varName, index, ReflectionArrayVariableReference.VARIABLE_HASHTABLE);
	}
	RESULT = var;
:}

| compound_variable:comp_var
{: RESULT = comp_var; :}
;

compound_variable ::=
tracked_variable:var
{: RESULT = var; :}

| T_DOLLAR:start T_CURLY_OPEN expr:expr T_CURLY_CLOSE:end
{:
	ReflectionVariableReference var = new ReflectionVariableReference(startleft, endright, expr);
	RESULT = var;	 
:}	
;

dim_offset ::=
expr:expr 
{: 
	RESULT = expr; 
:}
;

object_property ::=
object_dim_list:var
{: 
	RESULT = var; 
:}

| variable_without_objects:var
{:
	RESULT = var;
:}
;

object_dim_list ::=
object_dim_list:var T_OPEN_RECT dim_offset:index T_CLOSE_RECT:end
{:
	Expression varArray;
	if(var.getKind() == ExpressionConstants.E_IDENTIFIER) { // VariableReference - $a
		varArray = new ArrayVariableReference(varleft, endright, ((SimpleReference)var).getName(), index, ArrayVariableReference.VARIABLE_ARRAY);
	} else {
		varArray = new ReflectionArrayVariableReference(varleft, endright, var, index, ReflectionArrayVariableReference.VARIABLE_ARRAY);
	}
	RESULT = varArray;	
:}

| object_dim_list:var T_CURLY_OPEN expr:index T_CURLY_CLOSE:end
{:
	Expression varArray;
	if(var.getKind() == ExpressionConstants.E_IDENTIFIER) { // VariableReference - $a
		varArray = new ArrayVariableReference(varleft, endright, ((SimpleReference)var).getName(), index, ArrayVariableReference.VARIABLE_HASHTABLE);
	} else {
		varArray = new ReflectionArrayVariableReference(varleft, endright, var, index, ReflectionArrayVariableReference.VARIABLE_HASHTABLE);
	}
	RESULT = varArray;	
:}
;

variable_name ::=
T_STRING:varName
{:
	RESULT = new SimpleReference(varNameleft, varNameright, varName); 
:}

| T_CURLY_OPEN:start expr:expr T_CURLY_CLOSE:end
{:
	RESULT = new ReflectionVariableReference(startleft, endright, expr); 
:}
;

simple_indirect_reference ::=
T_DOLLAR 
{:
	RESULT = new Integer(1);
:}

| simple_indirect_reference:ref T_DOLLAR
{:
	RESULT = new Integer(1 + ref.intValue());
:}
;

assignment_list ::=
assignment_list:listElements T_COMMA assignment_list_element:element
{:
	if (element != null) {
		listElements.add(element);
	}
	RESULT = listElements;
:}

| assignment_list_element:var
{:
	List listElements = new LinkedList();
	if (var != null) {
		listElements.add(var);	
	}
	RESULT = listElements;
	;
:}
;

assignment_list_element ::=
variable:var
{:
	RESULT = var;
:}

| T_LIST:start T_OPEN_PARENTHESE assignment_list:varList T_CLOSE_PARENTHESE:end
{:
	ListVariable vars = new ListVariable(startleft, endright, varList);
	RESULT = vars;
:}

| /* empty */
{:
	RESULT = null;
:}
;

object_pair_list ::=
/* empty */
{:
	List list = new LinkedList();
	RESULT = list;	
:}

| non_empty_object_pair_list:list possible_comma
{:
	RESULT = list;
:}
;


non_empty_object_pair_list ::=
non_empty_object_pair_list:list T_COMMA expr:key T_NEKUDOTAIM expr:value
{:
	ArrayElement element = new ArrayElement(keyleft, valueright, key, value);
	list.add(element);
	RESULT = list;
:}

| expr:key T_NEKUDOTAIM expr:value
{:
	List list = new LinkedList();
	ArrayElement element = new ArrayElement(keyleft, valueright, key, value);
	list.add(element);
	RESULT = list;
:}

| non_empty_object_pair_list:list T_COMMA expr:expr
{:
	ArrayElement element = new ArrayElement(exprleft, exprright, expr);
	list.add(element);
	RESULT = list;
:}

| expr:expr
{:
	List list = new LinkedList();
	ArrayElement element = new ArrayElement(exprleft, exprright, expr);
	list.add(element);
	RESULT = list;
:}
;



array_pair_list ::=
/* empty */
{:
	List list = new LinkedList();
	RESULT = list;	
:}

| non_empty_array_pair_list:list 
{:
	RESULT = list;
:}
;

non_empty_array_pair_list ::=
non_empty_array_pair_list:list T_COMMA var_expr:expr
{:
	ArrayElement element = new ArrayElement(exprleft, exprright, expr);
	list.add(element);
	RESULT = list;
:}

| var_expr:expr
{:
	List list = new LinkedList();
	ArrayElement element = new ArrayElement(exprleft, exprright, expr);
	list.add(element);
	RESULT = list;
:}
;

encaps_list ::=
encaps_list:list encaps_var:var
{:
	list.add(var);
	RESULT = list;
:}

| encaps_list:list T_ENCAPSED_AND_WHITESPACE:string
{:
	Scalar scalar = new Scalar(stringleft, stringright, string, string == null ? Scalar.TYPE_UNKNOWN : Scalar.TYPE_STRING);
	list.add(scalar);
	RESULT = list;
:}

| encaps_var:var
{:
	List list = new LinkedList();
	list.add(var);
	RESULT = list;
:}

| T_ENCAPSED_AND_WHITESPACE:string encaps_var:var
{:
	List list = new LinkedList();
	Scalar scalar = new Scalar(stringleft, stringright, string, string == null ? Scalar.TYPE_UNKNOWN : Scalar.TYPE_STRING);
	list.add(scalar);
	list.add(var);
	RESULT = list;
:}
;

encaps_var ::=
tracked_variable:var
{:
	RESULT = var;
:}

| tracked_variable:varName T_OPEN_RECT encaps_var_offset:index T_CLOSE_RECT:end
{:
	VariableReference var = new ArrayVariableReference(varNameleft, endright, varName.getName(), index, ArrayVariableReference.VARIABLE_ARRAY);
	RESULT = var;
:}

| tracked_variable:var T_OBJECT_OPERATOR T_STRING:string
{:
	VariableReference property = new VariableReference(stringleft, stringright, string);
	Expression dispatch = parser.createDispatch(var, property);
	RESULT = dispatch;
:}

| T_DOLLAR_OPEN_CURLY_BRACES:start expr:expr T_CURLY_CLOSE:end
{:
	ReflectionVariableReference var = new ReflectionVariableReference(startleft, endright, expr);
	RESULT = var;
:}	

| T_DOLLAR_OPEN_CURLY_BRACES:start T_STRING_VARNAME:varName T_OPEN_RECT expr:index T_CLOSE_RECT T_CURLY_CLOSE:end
{:
	VariableReference indexedVar = new ArrayVariableReference(startleft, endright, varName, index, ArrayVariableReference.VARIABLE_ARRAY);
	RESULT = indexedVar;
:}

| T_CURLY_OPEN_WITH_DOLAR:start variable:var T_CURLY_CLOSE:end
{:
	ReflectionVariableReference ref = new ReflectionVariableReference(startleft, endright, var);
	RESULT = ref;
:}
;

encaps_var_offset ::=
T_STRING:string
{:
	Scalar scalar = new Scalar(stringleft,stringright, string, Scalar.TYPE_STRING);
	RESULT = scalar;
:}

| T_NUM_STRING:num
{:
	Scalar scalar = new Scalar(numleft,numright, num, Scalar.TYPE_REAL);
	RESULT = scalar;	
:}
;

internal_functions_in_yacc ::=
T_INCLUDE:include T_OPEN_PARENTHESE expr:expr T_CLOSE_PARENTHESE
{:
	Include result = new Include(includeleft, exprright, expr, Include.IT_INCLUDE);
	RESULT = result;
:}

| T_INCLUDE_ONCE:include  T_OPEN_PARENTHESE expr:expr T_CLOSE_PARENTHESE
{:
	Include result = new Include(includeleft, exprright, expr, Include.IT_INCLUDE_ONCE);
	RESULT = result;
:}

| T_REQUIRE:include  T_OPEN_PARENTHESE expr:expr T_CLOSE_PARENTHESE
{:
	Include result = new Include(includeleft, exprright, expr, Include.IT_REQUIRE);
	RESULT = result;
:}

;


class_constant ::=
class_name:className T_PAAMAYIM_NEKUDOTAYIM T_STRING:varName
{:
	ConstantReference name = new ConstantReference(varNameleft, varNameright, varName);
	StaticConstantAccess constant = new StaticConstantAccess(classNameleft, varNameright, className, name); 
	RESULT = constant;
:}
| variable_class_name:className T_PAAMAYIM_NEKUDOTAYIM T_STRING:varName
{:
	ConstantReference name = new ConstantReference(varNameleft, varNameright, varName);
	StaticConstantAccess constant = new StaticConstantAccess(classNameleft, varNameright, className, name); 
	RESULT = constant; 
:}
;

tracked_variable ::=
T_STRING:varName
{:
	RESULT = new VariableReference(varNameleft, varNameright, varName, PHPVariableKind.LOCAL);
:}
;

string_st ::=
T_STRING:value
{: RESULT = value; :}
;