//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.11 at 12:17:22 PM IST 
//


package org.wso2.developerstudio.eclipse.security.project.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}operation" maxOccurs="unbounded"/>
 *         &lt;element ref="{}bindings"/>
 *         &lt;element ref="{}policies"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}module"/>
 *           &lt;element ref="{}parameter"/>
 *           &lt;element ref="{}policyUUID"/>
 *           &lt;element ref="{}association"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="exposedAllTransports" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="rahas.sctissuer" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="serviceActive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="serviceDeployedTime" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="serviceDocumentation" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="successfullyAdded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="utEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operation",
    "bindings",
    "policies",
    "moduleOrParameterOrPolicyUUID"
})
@XmlRootElement(name = "service", namespace = "")
public class Service {

    @XmlElement(namespace = "", required = true)
    protected List<Operation> operation;
    @XmlElement(namespace = "", required = true)
    protected Bindings bindings;
    @XmlElement(namespace = "", required = true)
    protected Policies policies;
    @XmlElementRefs({
        @XmlElementRef(name = "module", type = Module.class, required = false),
        @XmlElementRef(name = "association", type = Association.class, required = false),
        @XmlElementRef(name = "policyUUID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "parameter", type = Parameter.class, required = false)
    })
    protected List<Object> moduleOrParameterOrPolicyUUID;
    @XmlAttribute(name = "exposedAllTransports", required = true)
    protected boolean exposedAllTransports;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlAttribute(name = "rahas.sctissuer")
    protected Boolean rahasSctissuer;
    @XmlAttribute(name = "serviceActive")
    protected Boolean serviceActive;
    @XmlAttribute(name = "serviceDeployedTime", required = true)
    protected BigInteger serviceDeployedTime;
    @XmlAttribute(name = "serviceDocumentation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String serviceDocumentation;
    @XmlAttribute(name = "successfullyAdded", required = true)
    protected boolean successfullyAdded;
    @XmlAttribute(name = "utEnabled")
    protected Boolean utEnabled;

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Operation }
     * 
     * 
     */
    public List<Operation> getOperation() {
        if (operation == null) {
            operation = new ArrayList<Operation>();
        }
        return this.operation;
    }

    /**
     * Gets the value of the bindings property.
     * 
     * @return
     *     possible object is
     *     {@link Bindings }
     *     
     */
    public Bindings getBindings() {
        return bindings;
    }

    /**
     * Sets the value of the bindings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bindings }
     *     
     */
    public void setBindings(Bindings value) {
        this.bindings = value;
    }

    /**
     * Gets the value of the policies property.
     * 
     * @return
     *     possible object is
     *     {@link Policies }
     *     
     */
    public Policies getPolicies() {
        return policies;
    }

    /**
     * Sets the value of the policies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Policies }
     *     
     */
    public void setPolicies(Policies value) {
        this.policies = value;
    }

    /**
     * Gets the value of the moduleOrParameterOrPolicyUUID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moduleOrParameterOrPolicyUUID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModuleOrParameterOrPolicyUUID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameter }
     * {@link Module }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Association }
     * 
     * 
     */
    public List<Object> getModuleOrParameterOrPolicyUUID() {
        if (moduleOrParameterOrPolicyUUID == null) {
            moduleOrParameterOrPolicyUUID = new ArrayList<Object>();
        }
        return this.moduleOrParameterOrPolicyUUID;
    }

    /**
     * Gets the value of the exposedAllTransports property.
     * 
     */
    public boolean isExposedAllTransports() {
        return exposedAllTransports;
    }

    /**
     * Sets the value of the exposedAllTransports property.
     * 
     */
    public void setExposedAllTransports(boolean value) {
        this.exposedAllTransports = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the rahasSctissuer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRahasSctissuer() {
        return rahasSctissuer;
    }

    /**
     * Sets the value of the rahasSctissuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRahasSctissuer(Boolean value) {
        this.rahasSctissuer = value;
    }

    /**
     * Gets the value of the serviceActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServiceActive() {
        return serviceActive;
    }

    /**
     * Sets the value of the serviceActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServiceActive(Boolean value) {
        this.serviceActive = value;
    }

    /**
     * Gets the value of the serviceDeployedTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServiceDeployedTime() {
        return serviceDeployedTime;
    }

    /**
     * Sets the value of the serviceDeployedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServiceDeployedTime(BigInteger value) {
        this.serviceDeployedTime = value;
    }

    /**
     * Gets the value of the serviceDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDocumentation() {
        return serviceDocumentation;
    }

    /**
     * Sets the value of the serviceDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDocumentation(String value) {
        this.serviceDocumentation = value;
    }

    /**
     * Gets the value of the successfullyAdded property.
     * 
     */
    public boolean isSuccessfullyAdded() {
        return successfullyAdded;
    }

    /**
     * Sets the value of the successfullyAdded property.
     * 
     */
    public void setSuccessfullyAdded(boolean value) {
        this.successfullyAdded = value;
    }

    /**
     * Gets the value of the utEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUtEnabled() {
        return utEnabled;
    }

    /**
     * Sets the value of the utEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUtEnabled(Boolean value) {
        this.utEnabled = value;
    }

}
