<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="esb"
    nsURI="http:///org/wso2/developerstudio/eclipse/esb" nsPrefix="esb">
  <eClassifiers xsi:type="ecore:EClass" name="ModelObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectState" eType="#//ModelObjectState"
        defaultValueLiteral="NORMAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultNamespace" eType="#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalNamespaces" upperBound="-1"
        eType="#//Namespace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentEsbVersion" eType="#//EsbVersion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelObjectState">
    <eLiterals name="NORMAL"/>
    <eLiterals name="WORKING" value="1"/>
    <eLiterals name="INCOMPLETE" value="2"/>
    <eLiterals name="INVALID" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynapseConfiguration" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationElements"
        lowerBound="1" upperBound="-1" eType="#//ConfigurationElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default_location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationElement" abstract="true"
      eSuperTypes="#//ModelObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mediator" abstract="true" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Description"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndPointReference" abstract="true" eSuperTypes="#//ModelObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndPoint" abstract="true" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="endpoint_name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnknownObject" eSuperTypes="#//ConfigurationElement #//EndPoint #//Mediator"/>
  <eClassifiers xsi:type="ecore:EClass" name="MediatorSequence" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="sequence_name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediators" upperBound="-1"
        eType="#//Mediator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onError" eType="#//RegistryKeyProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//Description"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediatorBranch" abstract="true" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Mediator" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentMediator" abstract="true" eSuperTypes="#//Mediator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Mediator" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamespacedProperty" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prettyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Namespaced Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="propertyName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaces">
      <eGenericType eClassifier="#//Map">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Map" instanceClassName="java.util.Map">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegistryKeyProperty" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prettyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Registry Key"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="keyName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filters">
      <eGenericType eClassifier="#//Map">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNameValueProperty" abstract="true"
      eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="property_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="property_value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNameValueExpressionProperty"
      abstract="true" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="property_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValueType" eType="#//PropertyValueType"
        defaultValueLiteral="VALUE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="property_value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyExpression" eType="#//NamespacedProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameValueTypeProperty" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PropertyName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PropertyType" lowerBound="1"
        eType="#//TaskPropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PropertyValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskPropertyType">
    <eLiterals name="Literal"/>
    <eLiterals name="XML" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyValueType">
    <eLiterals name="VALUE"/>
    <eLiterals name="EXPRESSION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBooleanFeature" abstract="true"
      eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="feature_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractLocationKeyResource" abstract="true"
      eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default_location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//RegistryKeyProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCommonTarget" abstract="true"
      eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceType" eType="#//TargetSequenceType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" eType="#//MediatorSequence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceKey" eType="#//RegistryKeyProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointType" eType="#//TargetEndpointType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" eType="#//EndPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointKey" eType="#//RegistryKeyProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TargetSequenceType">
    <eLiterals name="NONE"/>
    <eLiterals name="ANONYMOUS" value="1"/>
    <eLiterals name="REGISTRY_REFERENCE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TargetEndpointType">
    <eLiterals name="NONE"/>
    <eLiterals name="ANONYMOUS" value="1"/>
    <eLiterals name="REGISTRY_REFERENCE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEndPoint" abstract="true" eSuperTypes="#//EndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliableMessagingEnabled"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressingEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressingVersion" eType="#//EndPointAddressingVersion"
        defaultValueLiteral="final"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressingSeparateListener"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOutDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOutAction" eType="#//EndPointTimeOutAction"
        defaultValueLiteral="discard"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryErrorCodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retryDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendErrorCodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendInitialDuration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendMaximumDuration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendProgressionFactor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliableMessagingPolicy"
        eType="#//RegistryKeyProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityPolicy" eType="#//RegistryKeyProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EndPointAddressingVersion">
    <eLiterals name="FINAL" literal="final"/>
    <eLiterals name="SUBMISSION" value="1" literal="submission"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EndPointTimeOutAction">
    <eLiterals name="DISCARD" literal="discard"/>
    <eLiterals name="FAULT" value="1" literal="fault"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EndPointMessageFormat">
    <eLiterals name="LEAVE_AS_IS"/>
    <eLiterals name="SOAP_1_1" value="1" literal="soap11"/>
    <eLiterals name="SOAP_1_2" value="2" literal="soap12"/>
    <eLiterals name="POX" value="3" literal="pox"/>
    <eLiterals name="GET" value="4" literal="get"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EndPointAttachmentOptimization">
    <eLiterals name="LEAVE_AS_IS"/>
    <eLiterals name="MTOM" value="1" literal="mtom"/>
    <eLiterals name="SWA" value="2" literal="swa"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDefaultEndPoint" abstract="true"
      eSuperTypes="#//AbstractEndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageFormat" eType="#//EndPointMessageFormat"
        defaultValueLiteral="LEAVE_AS_IS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attachmentOptimization"
        eType="#//EndPointAttachmentOptimization" defaultValueLiteral="LEAVE_AS_IS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="UTF-8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statisticsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restType" eType="#//EndPointMessageFormatRestType"
        defaultValueLiteral="get"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultEndPoint" eSuperTypes="#//AbstractDefaultEndPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddressEndPoint" eSuperTypes="#//AbstractDefaultEndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://default/address/endpoint/uri"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EndPointWsdlType">
    <eLiterals name="URI"/>
    <eLiterals name="INLINE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsdlEndPoint" eSuperTypes="#//AbstractEndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlType" eType="#//EndPointWsdlType"
        defaultValueLiteral="URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://default/wsdl/uri"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlXML" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;definitions/>"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Service"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentEndPoint" abstract="true" eSuperTypes="#//EndPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//EndPoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailoverEndPoint" eSuperTypes="#//ParentEndPoint"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadBalanceEndPoint" eSuperTypes="#//ParentEndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithm" eType="#//LoadBalanceAlgorithm"
        defaultValueLiteral="org.apache.synapse.endpoints.algorithms.RoundRobin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionType" eType="#//LoadBalanceSessionType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionTimeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LoadBalanceAlgorithm">
    <eLiterals name="ROUND_ROBIN" literal="org.apache.synapse.endpoints.algorithms.RoundRobin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LoadBalanceSessionType">
    <eLiterals name="NONE"/>
    <eLiterals name="TRANSPORT" value="1" literal="http"/>
    <eLiterals name="SOAP" value="2" literal="soap"/>
    <eLiterals name="CLIENT_ID" value="3" literal="simpleClientSession"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicLoadBalanceEndPoint" eSuperTypes="#//EndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithm" eType="#//LoadBalanceAlgorithm"
        defaultValueLiteral="ROUND_ROBIN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failoverEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="membershipHandlerClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="class_name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//DynamicLoadBalanceProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicLoadBalanceProperty" eSuperTypes="#//AbstractNameValueProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="XPathEndPointReference" eSuperTypes="#//EndPointReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointXpath" eType="#//NamespacedProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegistryKeyEndPointReference" eSuperTypes="#//EndPointReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointKey" eType="#//RegistryKeyProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyService" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="service_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinnedServers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statisticsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transports" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="https,http"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reliableMessagingEnabled"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsdlConfiguration" eType="#//ProxyWsdlConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inSequenceConfiguration"
        eType="#//ProxyInSequenceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointConfiguration"
        eType="#//ProxyEndpointConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outSequenceConfiguration"
        eType="#//ProxyOutSequenceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faultSequenceConfiguration"
        eType="#//ProxyFaultSequenceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceParameters" upperBound="-1"
        eType="#//ProxyServiceParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicePolicies" upperBound="-1"
        eType="#//ProxyServicePolicy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyWsdlConfiguration" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlType" eType="#//ProxyWsdlType"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlXML" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;definitions/>"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wsdlURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://default/wsdl/url"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsdlKey" eType="#//RegistryKeyProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsdlResources" upperBound="-1"
        eType="#//ProxyWsdlResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProxyWsdlType">
    <eLiterals name="NONE"/>
    <eLiterals name="INLINE" value="1"/>
    <eLiterals name="SOURCE_URL" value="2"/>
    <eLiterals name="REGISTRY_KEY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyWsdlResource" eSuperTypes="#//AbstractLocationKeyResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyServiceParameter" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameter_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="parameter_value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyServicePolicy" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyKey" eType="#//RegistryKeyProperty"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProxySequenceConfiguration"
      abstract="true" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceType" eType="#//ProxySequenceType"
        defaultValueLiteral="ANONYMOUS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inlineSequence" eType="#//MediatorSequence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceKey" eType="#//RegistryKeyProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="sequence_name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProxySequenceType">
    <eLiterals name="NONE"/>
    <eLiterals name="ANONYMOUS" value="1"/>
    <eLiterals name="REGISTRY_REFERENCE" value="2"/>
    <eLiterals name="NAMED_REFERENCE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyInSequenceConfiguration" eSuperTypes="#//AbstractProxySequenceConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyEndpointConfiguration" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointType" eType="#//ProxyEndpointType"
        defaultValueLiteral="ANONYMOUS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inlineEndpoint" eType="#//EndPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpointKey" eType="#//RegistryKeyProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="endpoint_name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProxyEndpointType">
    <eLiterals name="NONE"/>
    <eLiterals name="ANONYMOUS" value="1"/>
    <eLiterals name="REGISTRY_REFERENCE" value="2"/>
    <eLiterals name="NAMED_REFERENCE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyOutSequenceConfiguration" eSuperTypes="#//AbstractProxySequenceConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProxyFaultSequenceConfiguration" eSuperTypes="#//AbstractProxySequenceConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalEntry" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="entry_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="#//LocalEntryValueType"
        defaultValueLiteral="LITERAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="entry_value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueXML" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&lt;value/>"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="file:/path/to/resource.ext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LocalEntryValueType">
    <eLiterals name="LITERAL"/>
    <eLiterals name="XML" value="1"/>
    <eLiterals name="URL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluatorExpressionProperty" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prettyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluatorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluatorValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EsbVersion">
    <eLiterals name="ESB301" literal="ESB301"/>
    <eLiterals name="ESB400" value="1" literal="ESB400"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EndPointMessageFormatRestType">
    <eLiterals name="GET" literal="get"/>
    <eLiterals name="POST" value="1" literal="rest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskImplementation" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TaskImplementation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="org.apache.synapse.startup.tasks.MessageInjector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskProperties" upperBound="-1"
        eType="#//TaskProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskProperty" eSuperTypes="#//NameValueTypeProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TaskName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TaskGroup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="synapse.simple.quartz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskImplementationClass"
        eType="#//TaskImplementation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TriggerType" lowerBound="1"
        eType="#//TaskTriggerType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Interval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cron" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PinnedServers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TaskTriggerType">
    <eLiterals name="Simple"/>
    <eLiterals name="Cron" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApiInSequenceConfiguration" eSuperTypes="#//AbstractProxySequenceConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApiOutSequenceConfiguration" eSuperTypes="#//AbstractProxySequenceConfiguration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApiFaultSequenceConfiguration" eSuperTypes="#//AbstractProxySequenceConfiguration"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ApiResourceUrlStyle">
    <eLiterals name="NONE" literal="None"/>
    <eLiterals name="URI_TEMPLATE" value="1" literal="URI-Template"/>
    <eLiterals name="URL_MAPPING" value="2" literal="URL-Mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApiResource" eSuperTypes="#//ModelObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inSequenceConfiguration"
        eType="#//ApiInSequenceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outSequenceConfiguration"
        eType="#//ApiOutSequenceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faultSequenceConfiguration"
        eType="#//ApiFaultSequenceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlStyle" lowerBound="1"
        eType="#//ApiResourceUrlStyle" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriTemplate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="urlMapping" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowGet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowPost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowPut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowDelete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowOptions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SynapseAPI" eSuperTypes="#//ConfigurationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="api_name"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="/context"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//ApiResource" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
