<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="record"
    nsURI="http://www.wso2.org/developerstudio/bps/humantask" nsPrefix="rec">
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionElement" abstract="true" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//BPELExtensibleElement">
    <eOperations name="fixElement" eType="ecore:EDataType platform:/plugin/org.eclipse.wst.wsdl/model/WSDL.ecore#//DOMElement">
      <eParameters name="document" eType="ecore:EDataType platform:/plugin/org.eclipse.wst.wsdl/model/WSDL.ecore#//DOMDocument"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
