/**
 *
 * $Id$
 */
package org.wso2.developerstudio.datamapper.validation;

import org.wso2.developerstudio.datamapper.InNode;
import org.wso2.developerstudio.datamapper.OutNode;

/**
 * A sample validator interface for {@link org.wso2.developerstudio.datamapper.DataMapperLink}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataMapperLinkValidator {
	boolean validate();

	boolean validateInNode(InNode value);
	boolean validateOutNode(OutNode value);
}
