/**
 *
 * $Id$
 */
package org.wso2.developerstudio.datamapper.validation;


/**
 * A sample validator interface for {@link java.util.Map.Entry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyKeyValuePairValidator {
	boolean validate();

	boolean validateKey(String value);

	boolean validateValue(String value);

	boolean validateTypedKey(String value);
	boolean validateTypedValue(String value);
}
