<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://eclipse.org/bpel/extensionsample" nsPrefix="extensionsample">
  <eClassifiers xsi:type="ecore:EClass" name="SampleSimpleActivity" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensionActivity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SampleExtensionAttribute"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampleStructuredActivity" eSuperTypes="../../org.eclipse.bpel.model/src/model/bpel.ecore#//ExtensionActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.bpel.model/src/model/bpel.ecore#//Activity"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
