#!/bin/sh

 
rm XmlSchema*.jar 
rm axiom_*.jar 
rm bsf-all_*.jar 
rm com.google.guava_*.jar 
rm commons-codec_*.jar 
rm commons-collections_*.jar 
rm commons-httpclient_*.jar 
rm commons-io_*.jar 
rm commons-lang_*.jar 
rm handy-uri-templates_*.jar 
rm httpcore_*.jar 
rm jackson-annotations_*.jar 
rm jackson-core_*.jar 
rm jackson-databind_*.jar 
rm jettison_*.jar 
rm joda-time_*.jar 
rm js_*.jar 
rm json-schema-validator-all_*.jar 
rm json_*.jar 
rm libphonenumber_*.jar 
rm neethi_*.jar 
rm org.eclipse.osgi_*.jar 
rm org.wso2.carbon.authenticator.proxy_*.jar 
rm org.wso2.carbon.base_*.jar 
rm org.wso2.carbon.base_*.jar 
rm org.wso2.carbon.core_*.jar 
rm org.wso2.carbon.databridge.commons_*.jar 
rm org.wso2.carbon.event.core_*.jar 
rm org.wso2.carbon.event.ws_*.jar 
rm org.wso2.carbon.identity.entitlement.mediator_*.jar 
rm org.wso2.carbon.identity.entitlement.proxy_*.jar 
rm org.wso2.carbon.identity.oauth.mediator_*.jar 
rm org.wso2.carbon.mediator.bam.config_*.jar 
rm org.wso2.carbon.mediator.bam_*.jar 
rm org.wso2.carbon.mediator.cache_*.jar 
rm org.wso2.carbon.mediator.datamapper_*.jar 
rm org.wso2.carbon.mediator.event_*.jar 
rm org.wso2.carbon.mediator.fastXSLT_*.jar 
rm org.wso2.carbon.mediator.publishevent_*.jar 
rm org.wso2.carbon.mediator.router.impl_*.jar 
rm org.wso2.carbon.mediator.router.impl_*.jar 
rm org.wso2.carbon.mediator.service_*.jar 
rm org.wso2.carbon.mediator.smooks_*.jar 
rm org.wso2.carbon.registry.api_*.jar 
rm org.wso2.carbon.registry.core_*.jar 
rm org.wso2.carbon.relay.mediators.builder_*.jar 
rm org.wso2.carbon.relay_*.jar 
rm org.wso2.carbon.rule.backend_*.jar 
rm org.wso2.carbon.rule.common_*.jar 
rm org.wso2.carbon.rule.kernel_*.jar 
rm org.wso2.carbon.rule.mediation_*.jar 
rm org.wso2.carbon.securevault_*.jar 
rm org.wso2.carbon.user.api_*.jar 
rm org.wso2.carbon.user.core_*.jar 
rm org.wso2.carbon.utils_*.jar 
rm org.wso2.securevault_*.jar 
rm quartz_*.jar 
rm rampart-core_*.jar 
rm rampart-policy_*.jar 
rm rampart-trust_*.jar 
rm smooks_*.jar 
rm spring.framework_*.jar 
rm synapse-commons_*.jar 
rm synapse-core_*.jar 
rm synapse-core_*.jar 
rm synapse-extensions_*.jar 
rm synapse-fix-transport_*.jar 
rm synapse-nhttp-transport_*.jar 
rm synapse-samples_*.jar 
rm synapse-tasks_*.jar 
rm synapse-vfs-transport_*.jar 
rm tomcat-*.jar 
rm woden_*.jar 
rm wsdl4j_*.jar 
rm xmlbeans_*.jar 

