<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datamapper" nsURI="http:///org/wso2/developerstudio/eclipse/gmf/datamapper"
    nsPrefix="datamapper">
  <eClassifiers xsi:type="ecore:EClass" name="DataMapperNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trim" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clone" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Replace" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$Target}"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replaceString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$ReplaceWith}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$Pattern}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Min" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Max" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomFunction" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="customFunction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="function(in1,in2){ return (in1 + in2);};"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputConnectorTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Result"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InputConnectorTag" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="In"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Properties" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default_name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="DEFAULT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compare" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparisonOperator" eType="#//ComparisonOperatorType"
        defaultValueLiteral="=="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperatorType">
    <eLiterals name="EQUAL_VALUE" literal="=="/>
    <eLiterals name="EQUAL_VALUE_TYPE" value="1" literal="==="/>
    <eLiterals name="NOT_EQUAL_VALUE" value="2" literal="!="/>
    <eLiterals name="NOT_EQUAL_VALUE_TYPE" value="3" literal="!=="/>
    <eLiterals name="GREATER_THAN" value="4" literal=">"/>
    <eLiterals name="GREATER_OR_EQUAL" value="5" literal=">="/>
    <eLiterals name="LOWER_THAN" value="6" literal="&lt;"/>
    <eLiterals name="LOWER_OR_EQUAL" value="7" literal="&lt;="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToNumber" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToBoolean" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataMapperRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Input"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//Output"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operators" upperBound="-1"
        eType="#//Operator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLength" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartsWith" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$Pattern}"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getPatternFromInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndsWith" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$Pattern}"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getPatternFromInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Substring" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$StartIndex}"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$Length}"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getPatternFromInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfElse" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="getPatternFromInput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//DataMapperNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeNode" upperBound="-1"
        eType="#//TreeNode" containment="true" eOpposite="#//TreeNode/inputParent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NOT" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//DataMapperNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treeNode" upperBound="-1"
        eType="#//TreeNode" containment="true" eOpposite="#//TreeNode/outputParent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" eSuperTypes="#//DataMapperNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicContainer" eType="#//OperatorBasicContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultInputConnectors"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultOutputConnectors"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputSizeFixed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputSizeFixed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorType" eType="#//DataMapperOperatorType"
        defaultValueLiteral="OPERATOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorBasicContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftContainer" eType="#//OperatorLeftContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightContainer" eType="#//OperatorRightContainer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorLeftContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftConnectors" upperBound="-1"
        eType="#//OperatorLeftConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorLeftConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inNode" eType="#//InNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorRightContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightConnectors" upperBound="-1"
        eType="#//OperatorRightConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatorRightConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outNode" eType="#//OutNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outNode" eType="#//OutNode"
        containment="true" eOpposite="#//OutNode/elementParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inNode" eType="#//InNode"
        containment="true" eOpposite="#//InNode/elementParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldParent" eType="#//TreeNode"
        eOpposite="#//TreeNode/element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaDataType" eType="#//SchemaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        upperBound="-1" eType="#//PropertyKeyValuePair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//TreeNode"
        containment="true" eOpposite="#//TreeNode/fieldParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
        eType="#//Element" containment="true" eOpposite="#//Element/fieldParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldParent" eType="#//TreeNode"
        eOpposite="#//TreeNode/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputParent" eType="#//Output"
        eOpposite="#//Output/treeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputParent" eType="#//Input"
        eOpposite="#//Input/treeNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaDataType" eType="#//SchemaDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        upperBound="-1" eType="#//PropertyKeyValuePair" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outNode" eType="#//OutNode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inNode" eType="#//InNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subtract" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="InNode">
    <eOperations name="shouldConnect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="sourceEnd" eType="#//OutNode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLink" upperBound="-1"
        eType="#//DataMapperLink" eOpposite="#//DataMapperLink/inNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementParent" eType="#//Element"
        eOpposite="#//Element/inNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutNode">
    <eOperations name="shouldConnect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="targetEnd" eType="#//InNode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLink" upperBound="-1"
        eType="#//DataMapperLink" containment="true" eOpposite="#//DataMapperLink/outNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementParent" eType="#//Element"
        eOpposite="#//Element/outNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataMapperLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inNode" eType="#//InNode"
        eOpposite="#//InNode/incomingLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outNode" eType="#//OutNode"
        eOpposite="#//OutNode/outgoingLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concat" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteValue" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equal" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constantValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SchemaDataType"
        defaultValueLiteral="STRING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Divide" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Floor" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Round" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiply" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetPrecision" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDigits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="{$NoOfDigits}"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Split" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayOutput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayOutputResultOmitingIndices"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchemaDataType">
    <eLiterals name="ARRAY"/>
    <eLiterals name="BOOLEAN" value="1"/>
    <eLiterals name="BYTES" value="2"/>
    <eLiterals name="DOUBLE" value="3"/>
    <eLiterals name="ENUM" value="4"/>
    <eLiterals name="FIXED" value="5"/>
    <eLiterals name="FLOAT" value="6"/>
    <eLiterals name="INT" value="7"/>
    <eLiterals name="LONG" value="8"/>
    <eLiterals name="MAP" value="9"/>
    <eLiterals name="NULL" value="10"/>
    <eLiterals name="OBJECT" value="11"/>
    <eLiterals name="STRING" value="12"/>
    <eLiterals name="UNION" value="13"/>
    <eLiterals name="NUMBER" value="14" literal="NUMBER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataMapperOperatorType">
    <eLiterals name="OPERATOR"/>
    <eLiterals name="COMMON_OPERATION" value="1"/>
    <eLiterals name="DIRECT" value="21"/>
    <eLiterals name="STRING_OPERATION" value="2"/>
    <eLiterals name="ARITHMATIC_OPERATION" value="2"/>
    <eLiterals name="BOOLEAN_OPERATION" value="3"/>
    <eLiterals name="CONDITIONAL_OPERATION" value="4"/>
    <eLiterals name="CONSTANT" value="5"/>
    <eLiterals name="EQUALS" value="6"/>
    <eLiterals name="CONCAT" value="7"/>
    <eLiterals name="SPLIT" value="8"/>
    <eLiterals name="UPPERCASE" value="9"/>
    <eLiterals name="LOWERCASE" value="10"/>
    <eLiterals name="CONTAINS" value="11"/>
    <eLiterals name="ADD" value="12"/>
    <eLiterals name="SUBTRACT" value="13"/>
    <eLiterals name="MULTIPLY" value="14"/>
    <eLiterals name="DIVIDE" value="15"/>
    <eLiterals name="ABSOLUTE" value="16"/>
    <eLiterals name="ROUND" value="17"/>
    <eLiterals name="FLOOR" value="18"/>
    <eLiterals name="CEILING" value="19"/>
    <eLiterals name="SET_PRECISION" value="20"/>
    <eLiterals name="AND" value="21" literal="AND"/>
    <eLiterals name="OR" value="22"/>
    <eLiterals name="NOT" value="23"/>
    <eLiterals name="ENDS_WITH" value="24"/>
    <eLiterals name="IF_ELSE" value="25"/>
    <eLiterals name="STARTS_WITH" value="26"/>
    <eLiterals name="STRING_LENGTH" value="27"/>
    <eLiterals name="SUBSTRING" value="28"/>
    <eLiterals name="COMPARE" value="29"/>
    <eLiterals name="CUSTOM_FUNCTION" value="30"/>
    <eLiterals name="MATCH" value="31"/>
    <eLiterals name="MAX" value="32"/>
    <eLiterals name="MIN" value="33"/>
    <eLiterals name="PROPERTIES" value="34"/>
    <eLiterals name="REPLACE" value="35"/>
    <eLiterals name="TRIM" value="38"/>
    <eLiterals name="TYPE_CONVERSION_OPERATION" value="39"/>
    <eLiterals name="STRING_TO_BOOLEAN" value="36"/>
    <eLiterals name="STRING_TO_NUMBER" value="37"/>
    <eLiterals name="INSTANTIATE" value="40"/>
    <eLiterals name="GET" value="41" literal="GET"/>
    <eLiterals name="TO_STRING" value="42"/>
    <eLiterals name="GLOBAL_VARIABLE" value="43"/>
    <eLiterals name="ADVANCED_CUSTOM_FUNCTION" value="44" literal="ADVANCED_CUSTOM_FUNCTION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowerCase" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Celi" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpperCase" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyKeyValuePair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToString" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalVariable" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="defaultName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;defaultValue&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdvancedCustomFunction" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="endFunction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="function(input,output){};"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEndFunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
</ecore:EPackage>
